"""Stable application contracts independent from a Codex SDK version."""

from __future__ import annotations

from enum import StrEnum


class AnswerStatus(StrEnum):
    ANSWERABLE = "ANSWERABLE"
    PARTIALLY_ANSWERABLE = "PARTIALLY_ANSWERABLE"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
    CAPABILITY_NOT_CONFIGURED = "CAPABILITY_NOT_CONFIGURED"
    FIELD_AVAILABLE_BUT_VALUE_MISSING = "FIELD_AVAILABLE_BUT_VALUE_MISSING"
    INFORMATION_NOT_IN_CONFIGURED_SOURCES = "INFORMATION_NOT_IN_CONFIGURED_SOURCES"
    ACCESS_RESTRICTED = "ACCESS_RESTRICTED"
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    CONFLICTING_SOURCES = "CONFLICTING_SOURCES"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNSUPPORTED_ACTION = "UNSUPPORTED_ACTION"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    SUCCEEDED = "SUCCEEDED"
    PARTIALLY_SUCCEEDED = "PARTIALLY_SUCCEEDED"
    FAILED = "FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
