from __future__ import annotations

from datetime import date
from io import BytesIO
import re

from django.core.exceptions import PermissionDenied, ValidationError
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

from .fleet_inventory_chat_service import _feature_enabled
from .models import AIConversationArtifact


class FleetExcelExportService:
    def __init__(self, user):
        self.user = user
        if not _feature_enabled("ENABLE_FLEET_EXCEL_EXPORT", user):
            raise PermissionDenied("Fleet Excel export is not enabled for this user.")

    def artifact(self, artifact_id) -> tuple[AIConversationArtifact, dict]:
        artifact = AIConversationArtifact.objects.select_related("conversation").filter(
            pk=artifact_id,
            conversation__user=self.user,
            artifact_type="fleet_equipment_table",
            status="active",
        ).first()
        if not artifact:
            raise PermissionDenied("The fleet export is unavailable.")
        payload = artifact.payload_json if isinstance(artifact.payload_json, dict) else {}
        value = payload.get("value") if isinstance(payload.get("value"), dict) else payload
        rows = value.get("rows") if isinstance(value.get("rows"), list) else []
        if not rows:
            raise ValidationError("The saved fleet result contains no rows.")
        return artifact, value

    @staticmethod
    def _safe_name(value: object, fallback: str) -> str:
        text = re.sub(r"[^A-Za-z0-9._-]+", "_", str(value or "").strip()).strip("._")
        return text[:80] or fallback

    def build(self, artifact_id) -> dict:
        artifact, payload = self.artifact(artifact_id)
        rows = payload["rows"]
        site = payload.get("site") or rows[0].get("site") or "Fleet"
        model = payload.get("model")
        workbook = Workbook()
        summary_sheet = workbook.active
        summary_sheet.title = "Fleet by Model"
        detail_sheet = workbook.create_sheet("Fleet Details")
        metadata_sheet = workbook.create_sheet("Export Metadata")

        counts = {}
        for row in rows:
            model_value = str(row.get("model") or "Unknown Model")
            counts[model_value] = counts.get(model_value, 0) + 1
        summary_sheet.append(["Site", "Model", "Equipment Count", "Share of Fleet"])
        for model_value, count in sorted(counts.items(), key=lambda item: (-item[1], item[0].casefold())):
            summary_sheet.append([site, model_value, count, count / len(rows)])
            summary_sheet.cell(summary_sheet.max_row, 2).number_format = "@"
            summary_sheet.cell(summary_sheet.max_row, 4).number_format = "0.0%"

        detail_sheet.append(["Site", "Equipment", "Model", "Serial Number"])
        for row in rows:
            detail_sheet.append([
                row.get("site") or "Not available",
                row.get("equipment") or "Not available",
                str(row.get("model") or "Unknown Model"),
                str(row.get("serial_number") or "Not available"),
            ])
            detail_sheet.cell(detail_sheet.max_row, 3).number_format = "@"
            detail_sheet.cell(detail_sheet.max_row, 4).number_format = "@"

        metadata_sheet.append(["Field", "Value"])
        metadata_sheet.append(["Generated By", "Mining360"])
        metadata_sheet.append(["Generated At", date.today().isoformat()])
        metadata_sheet.append(["MineSite", site])
        metadata_sheet.append(["Model Filter", model or "All models"])
        metadata_sheet.append(["Total Equipment", len(rows)])
        metadata_sheet.append(["Source Artifact ID", str(artifact.id)])

        for sheet in workbook.worksheets:
            sheet.freeze_panes = "A2"
            sheet.auto_filter.ref = sheet.dimensions
            for cell in sheet[1]:
                cell.font = Font(bold=True, color="FFFFFF")
                cell.fill = PatternFill("solid", fgColor="233746")
            for column in sheet.columns:
                letter = column[0].column_letter
                sheet.column_dimensions[letter].width = min(max(len(str(cell.value or "")) for cell in column) + 2, 42)

        output = BytesIO()
        workbook.save(output)
        output.seek(0)
        suffix = f"_Model_{self._safe_name(model, 'Model')}" if model else ""
        filename = f"Mining360_Fleet_{self._safe_name(site, 'Site')}{suffix}_{date.today().isoformat()}.xlsx"
        return {"content": output, "file_name": filename, "row_count": len(rows), "artifact": artifact}
