from __future__ import annotations

from datetime import date
from io import BytesIO
import re

from django.core.exceptions import PermissionDenied, ValidationError
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

from .fleet_inventory_chat_service import _feature_enabled
from .models import AIConversationArtifact


IDENTITY_COLUMNS = (
    ("Site", ("site", "minesite")),
    ("Equipment", ("equipment",)),
    ("Model", ("model",)),
    ("Serial Number", ("serial number", "serial_number", "sn")),
)
METRIC_COLUMNS = (
    ("Physical Availability", ("physical availability", "availability"), "0.00%"),
    ("MTBS", ("mtbs",), "0.00"),
    ("MTBF", ("mtbf",), "0.00"),
    ("MTTR", ("mttr",), "0.00"),
    ("Planned Downtime %", ("planned downtime", "planned downtime %"), "0.00%"),
    ("Unplanned Downtime %", ("unplanned downtime", "unplanned downtime %"), "0.00%"),
    ("Data Coverage", ("data coverage", "coverage percentage"), "0.00%"),
)


def _canonical_key(value: object) -> str:
    text = re.sub(r"^.*\[([^]]+)\]$", r"\1", str(value or "")).strip()
    return re.sub(r"[^a-z0-9]+", " ", text.casefold()).strip()


def _row_value(row: dict, aliases: tuple[str, ...]):
    normalized = {_canonical_key(key): value for key, value in row.items()}
    for alias in aliases:
        if _canonical_key(alias) in normalized:
            return normalized[_canonical_key(alias)]
    return None


class FleetPerformanceExcelExportService:
    def __init__(self, user):
        self.user = user
        if not (
            _feature_enabled("ENABLE_COMPLETE_FLEET_PERFORMANCE_CHAT", user)
            and _feature_enabled("ENABLE_FLEET_PERFORMANCE_EXPORT", user)
        ):
            raise PermissionDenied("Fleet Performance export is not enabled for this user.")

    def artifact(self, artifact_id) -> tuple[AIConversationArtifact, dict]:
        artifact = AIConversationArtifact.objects.select_related("conversation").filter(
            pk=artifact_id,
            conversation__user=self.user,
            artifact_type="fleet_performance_analysis",
            status="active",
        ).first()
        if not artifact:
            raise PermissionDenied("The Fleet Performance export is unavailable.")
        payload = artifact.payload_json if isinstance(artifact.payload_json, dict) else {}
        value = payload.get("value") if isinstance(payload.get("value"), dict) else payload
        rows = value.get("rows") if isinstance(value.get("rows"), list) else []
        if not rows:
            raise ValidationError("The saved Fleet Performance result contains no rows.")
        return artifact, value

    @staticmethod
    def _safe_name(value: object, fallback: str) -> str:
        text = re.sub(r"[^A-Za-z0-9._-]+", "_", str(value or "").strip()).strip("._")
        return text[:80] or fallback

    def build(self, artifact_id) -> dict:
        artifact, payload = self.artifact(artifact_id)
        rows = payload["rows"]
        metrics = payload.get("metrics") if isinstance(payload.get("metrics"), list) else []
        workbook = Workbook()
        summary = workbook.active
        summary.title = "Performance Summary"
        results = workbook.create_sheet("Performance Results")
        metadata = workbook.create_sheet("Export Metadata")

        summary.append(["Metric", "Value", "Raw Value", "Unit"])
        for metric in metrics:
            summary.append([
                metric.get("label") or metric.get("code"),
                metric.get("formatted_value") or "Not available",
                metric.get("raw_value"),
                metric.get("unit") or "",
            ])

        selected_columns = []
        for label, aliases in IDENTITY_COLUMNS:
            if any(_row_value(row, aliases) not in (None, "") for row in rows):
                selected_columns.append((label, aliases, "@"))
        for label, aliases, number_format in METRIC_COLUMNS:
            if any(_row_value(row, aliases) is not None for row in rows):
                selected_columns.append((label, aliases, number_format))
        if not selected_columns:
            selected_columns = [(str(key), (str(key),), "General") for key in rows[0].keys()]

        results.append([item[0] for item in selected_columns])
        for row in rows:
            results.append([_row_value(row, item[1]) for item in selected_columns])
            for index, (_, _, number_format) in enumerate(selected_columns, start=1):
                results.cell(results.max_row, index).number_format = number_format

        source = payload.get("source") if isinstance(payload.get("source"), dict) else {}
        metadata.append(["Field", "Value"])
        metadata.append(["Generated By", "Mining360"])
        metadata.append(["Generated At", date.today().isoformat()])
        metadata.append(["Intent", payload.get("intent_type") or "Fleet Performance"])
        metadata.append(["Metric Bundle", payload.get("metric_bundle") or "Custom"])
        metadata.append(["Semantic Model", source.get("semantic_model_name") or "FPR Global DB + RLS"])
        metadata.append(["Semantic Model ID", source.get("semantic_model_id") or ""])
        metadata.append(["Source Artifact ID", str(artifact.id)])
        metadata.append(["Result Rows", len(rows)])

        for sheet in workbook.worksheets:
            sheet.freeze_panes = "A2"
            sheet.auto_filter.ref = sheet.dimensions
            for cell in sheet[1]:
                cell.font = Font(bold=True, color="FFFFFF")
                cell.fill = PatternFill("solid", fgColor="233746")
            for column in sheet.columns:
                letter = column[0].column_letter
                sheet.column_dimensions[letter].width = min(
                    max(len(str(cell.value or "")) for cell in column) + 2,
                    42,
                )

        output = BytesIO()
        workbook.save(output)
        output.seek(0)
        context = payload.get("context") if isinstance(payload.get("context"), dict) else {}
        scope = context.get("minesite") or context.get("site") or context.get("model") or "Authorized_Fleet"
        filename = f"Mining360_Fleet_Performance_{self._safe_name(scope, 'Scope')}_{date.today().isoformat()}.xlsx"
        return {"content": output, "file_name": filename, "row_count": len(rows), "artifact": artifact}
