# Generated by Django 6.0.6 on 2026-09-14 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodexChatbotPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codex_chatbot_pilot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codex_chatbot_pilot',
            },
        ),
        migrations.CreateModel(
            name='CodexConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New conversation', max_length=180)),
                ('native_thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codex_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codex_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CodexMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('answer_status', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='codex_chatbot.codexconversation')),
            ],
            options={
                'db_table': 'codex_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodexRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='QUEUED', max_length=40)),
                ('question', models.TextField()),
                ('tool_code', models.CharField(blank=True, max_length=120)),
                ('native_thread_id', models.CharField(blank=True, max_length=255)),
                ('native_turn_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='codex_chatbot.codexconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codex_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codex_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodexEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=120)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('value_json', models.JSONField(default=dict)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='codex_chatbot.codexrun')),
            ],
            options={
                'db_table': 'codex_evidence',
                'ordering': ['retrieved_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='codexconversation',
            index=models.Index(fields=['owner', 'status', 'updated_at'], name='codex_conv_owner_status'),
        ),
        migrations.AddIndex(
            model_name='codexmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='codex_msg_conv_time'),
        ),
    ]
