# Generated by Django 6.0.6 on 2026-09-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codexrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codexrun',
            name='progress_label',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='codexrun',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codexrun',
            name='result_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_run', to='codex_chatbot.codexmessage'),
        ),
    ]
