# Generated by Django 6.0.6 on 2026-09-14 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex_chatbot', '0002_codexrun_heartbeat_at_codexrun_progress_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodexArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(default='CSV', max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(default='text/csv', max_length=120)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codex_artifacts', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='codex_chatbot.codexrun')),
            ],
            options={
                'db_table': 'codex_artifact',
                'ordering': ['-created_at'],
            },
        ),
    ]
