# Generated by Django 6.0.6 on 2026-09-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex_chatbot', '0003_codexartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='codexconversation',
            name='legacy_context',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='codexconversation',
            name='legacy_conversation_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='codexmessage',
            name='legacy_message_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='codexmessage',
            name='legacy_payload',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
