# Generated by Django 6.0.6 on 2026-07-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_key', models.CharField(db_index=True, max_length=120)),
                ('source_name', models.CharField(max_length=255)),
                ('object_kind', models.CharField(max_length=40)),
                ('object_name', models.CharField(max_length=512)),
                ('run_type', models.CharField(default='all', max_length=20)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_rows', models.IntegerField(default=0)),
                ('controls_count', models.IntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(blank=True, default=list)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
