# Generated by Django 6.0.6 on 2026-07-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_platformuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('source_view_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=30)),
                ('last_sync_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataBrowserSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True)),
                ('sql_statement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='reports.databrowser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBrowserColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('sql_name', models.CharField(max_length=128)),
                ('data_type', models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Decimal', 'Decimal'), ('Date', 'Date'), ('DateTime', 'DateTime'), ('Boolean', 'Boolean')], max_length=20)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='reports.databrowser')),
            ],
            options={
                'ordering': ['display_order', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('browser', 'sql_name'), name='unique_browser_sql_column')],
            },
        ),
    ]
