# Generated by Django 6.0.6 on 2026-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_databrowser_databrowsersynclog_databrowsercolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='databrowsercolumn',
            name='is_lookup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='lookup_filter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='lookup_label_column',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='lookup_source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='lookup_value_column',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
