# Generated by Django 6.0.6 on 2026-07-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_databrowsercolumn_is_lookup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databrowsercolumn',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
