# Generated by Codex on 2026-07-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_databrowsercolumn_is_unique"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="databrowser",
            table="BrowserList",
        ),
    ]
