# Generated by Django 6.0.6 on 2026-07-07 13:58

import django.db.models.deletion
from django.db import migrations, models


def seed_ai_config(apps, schema_editor):
    AIConfigSection = apps.get_model('reports', 'AIConfigSection')
    AIMetricMapping = apps.get_model('reports', 'AIMetricMapping')
    AIFilterMapping = apps.get_model('reports', 'AIFilterMapping')
    AISynonym = apps.get_model('reports', 'AISynonym')
    AIQuestionExample = apps.get_model('reports', 'AIQuestionExample')
    AIDaxTemplate = apps.get_model('reports', 'AIDaxTemplate')

    sections = {
        'performance': ('Performance', 'Performance semantic model configuration.'),
        'parts_sales': ('Parts Sales', 'Parts sales semantic model configuration.'),
        'planned_component_rebuild': ('Planned Component Rebuild', 'Planned component rebuild semantic model configuration.'),
    }
    section_objects = {}
    for code, (name, description) in sections.items():
        section, _ = AIConfigSection.objects.update_or_create(
            code=code,
            defaults={'name': name, 'description': description, 'is_active': True},
        )
        section_objects[code] = section

    metrics = {
        'performance': [
            ('availability', 'Availability', '[Availability New]'),
            ('physical_availability', 'Physical Availability', '[Physical Availability]'),
            ('mtbf', 'MTBF', '[MTBF]'),
            ('mttr', 'MTTR', '[MTTR]'),
            ('mtbs', 'MTBS', '[MTBS]'),
            ('downtime', 'Downtime', '[Downtime]'),
            ('idle_time', 'Idle Time', '[Idle Time]'),
            ('fuel_burn', 'Fuel Burn', '[Fuel Burn]'),
        ],
        'parts_sales': [
            ('sales_amount', 'Sales Amount', '[Sales Amount]'),
            ('parts_sales', 'Parts Sales', '[Parts Sales]'),
            ('parts_margin', 'Parts Margin', '[Parts Margin]'),
            ('parts_quantity', 'Parts Quantity', '[Parts Quantity]'),
        ],
        'planned_component_rebuild': [
            ('planned_rebuild_count', 'Planned Rebuild Count', '[Planned Rebuild Count]'),
            ('rebuild_cost', 'Rebuild Cost', '[Rebuild Cost]'),
            ('component_life', 'Component Life', '[Component Life]'),
            ('remaining_life', 'Remaining Life', '[Remaining Life]'),
        ],
    }
    for section_code, rows in metrics.items():
        for code, label, measure in rows:
            AIMetricMapping.objects.update_or_create(
                section=section_objects[section_code],
                metric_code=code,
                defaults={
                    'metric_label': label,
                    'powerbi_measure_name': measure,
                    'description': '',
                    'is_active': True,
                },
            )

    filters = {
        'performance': [
            ('minesite', 'Minesite', 'MineSiteList_MiningProd', 'MineSite', 'Text', False),
            ('model', 'Model', 'EquipmentList_MiningProd', 'Model', 'Text', False),
            ('family', 'Family', 'EquipmentList_MiningProd', 'ParentProductGroup', 'Text', False),
            ('serial_number', 'Serial Number', 'EquipmentList_MiningProd', 'SN', 'Text', False),
            ('period', 'Period', 'Date', 'Year Month', 'Text', False),
            ('customer', 'Customer', 'MineSiteList_MiningProd', 'CustomerCode', 'Text', False),
        ],
        'parts_sales': [
            ('customer', 'Customer', 'Customer', 'CustomerName', 'Text', False),
            ('period', 'Period', 'Date', 'Year Month', 'Text', False),
            ('part_number', 'Part Number', 'Parts', 'PartNumber', 'Text', False),
            ('product_family', 'Product Family', 'Parts', 'ProductFamily', 'Text', False),
            ('branch', 'Branch', 'Branch', 'BranchName', 'Text', False),
        ],
        'planned_component_rebuild': [
            ('minesite', 'Minesite', 'MineSite', 'MineSite', 'Text', False),
            ('component', 'Component', 'Component', 'ComponentName', 'Text', False),
            ('model', 'Model', 'Equipment', 'Model', 'Text', False),
            ('serial_number', 'Serial Number', 'Equipment', 'SerialNumber', 'Text', False),
            ('period', 'Period', 'Date', 'Year Month', 'Text', False),
        ],
    }
    for section_code, rows in filters.items():
        for code, label, table, column, data_type, required in rows:
            AIFilterMapping.objects.update_or_create(
                section=section_objects[section_code],
                filter_code=code,
                defaults={
                    'filter_label': label,
                    'powerbi_table_name': table,
                    'powerbi_column_name': column,
                    'data_type': data_type,
                    'is_required': required,
                    'is_active': True,
                },
            )

    synonyms = [
        ('metric', 'availability', 'availability'),
        ('metric', 'availability', 'disponibilite'),
        ('metric', 'availability', 'dispo'),
        ('metric', 'availability', 'PA'),
        ('metric', 'availability', 'physical availability'),
        ('minesite', 'minesite', 'site'),
        ('minesite', 'minesite', 'mine'),
        ('minesite', 'minesite', 'minesite'),
        ('minesite', 'Fekola', 'Fekola'),
        ('minesite', 'Fekola', 'mine Fekola'),
        ('minesite', 'Fekola', 'site Fekola'),
        ('model', 'model', 'modele'),
        ('model', 'model', 'model'),
        ('model', '777', '777'),
        ('model', '777', 'CAT 777'),
        ('model', '777', 'camion 777'),
        ('model', '777', 'truck 777'),
        ('model', 'truck', 'camion'),
        ('model', 'truck', 'truck'),
        ('model', 'truck', 'trucks'),
    ]
    for entity_type, canonical, synonym in synonyms:
        AISynonym.objects.update_or_create(
            section=section_objects['performance'],
            entity_type=entity_type,
            canonical_value=canonical,
            synonym_value=synonym,
            language='fr',
            defaults={'is_active': True},
        )

    examples = [
        (
            'Donne-moi l availability du Minesite Fekola, periode 2025-05, modele 777',
            {'section': 'performance', 'metric': 'availability', 'filters': {'minesite': 'Fekola', 'period': '2025-05', 'model': '777'}},
        ),
        (
            'Quelle est la disponibilite des camions de Fekola en mai 2025 ?',
            {'section': 'performance', 'metric': 'availability', 'filters': {'minesite': 'Fekola', 'period': '2025-05'}},
        ),
        (
            'Montre-moi le MTBF des 777 a Fekola sur 2025-05',
            {'section': 'performance', 'metric': 'mtbf', 'filters': {'minesite': 'Fekola', 'period': '2025-05', 'model': '777'}},
        ),
    ]
    for question, intent in examples:
        AIQuestionExample.objects.update_or_create(
            section=section_objects['performance'],
            question_text=question,
            defaults={'language': 'fr', 'expected_json_intent': intent, 'is_active': True},
        )

    default_template = (
        'EVALUATE\n'
        'SUMMARIZECOLUMNS(\n'
        '    {filters},\n'
        '    "{metric_label}", {measure}\n'
        ')'
    )
    for section in section_objects.values():
        AIDaxTemplate.objects.update_or_create(
            section=section,
            template_code='single_metric_by_filters',
            defaults={
                'template_name': 'Single metric by filters',
                'dax_template': default_template,
                'description': 'Controlled DAX template for one metric and configured filters.',
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_databrowser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfigSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_config_sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIQuestionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('language', models.CharField(default='fr', max_length=16)),
                ('expected_json_intent', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_examples', to='reports.aiconfigsection')),
            ],
            options={
                'db_table': 'ai_question_examples',
                'ordering': ['-updated_at', 'question_text'],
            },
        ),
        migrations.CreateModel(
            name='AIDaxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_code', models.CharField(max_length=120)),
                ('dax_template', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dax_templates', to='reports.aiconfigsection')),
            ],
            options={
                'db_table': 'ai_dax_templates',
                'ordering': ['template_name', 'template_code'],
                'constraints': [models.UniqueConstraint(fields=('section', 'template_code'), name='unique_ai_dax_template_code_per_section')],
            },
        ),
        migrations.CreateModel(
            name='AIFilterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_code', models.CharField(max_length=120)),
                ('filter_label', models.CharField(max_length=255)),
                ('powerbi_table_name', models.CharField(max_length=255)),
                ('powerbi_column_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_mappings', to='reports.aiconfigsection')),
            ],
            options={
                'db_table': 'ai_filter_mapping',
                'ordering': ['filter_label', 'filter_code'],
                'constraints': [models.UniqueConstraint(fields=('section', 'filter_code'), name='unique_ai_filter_code_per_section')],
            },
        ),
        migrations.CreateModel(
            name='AIMetricMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=120)),
                ('metric_label', models.CharField(max_length=255)),
                ('powerbi_measure_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_mappings', to='reports.aiconfigsection')),
            ],
            options={
                'db_table': 'ai_metric_mapping',
                'ordering': ['metric_label', 'metric_code'],
                'constraints': [models.UniqueConstraint(fields=('section', 'metric_code'), name='unique_ai_metric_code_per_section')],
            },
        ),
        migrations.CreateModel(
            name='AISynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('metric', 'Metric'), ('minesite', 'Minesite'), ('model', 'Model'), ('family', 'Family'), ('period', 'Period'), ('customer', 'Customer'), ('component', 'Component'), ('measure', 'Measure'), ('field', 'Field')], max_length=20)),
                ('canonical_value', models.CharField(max_length=255)),
                ('synonym_value', models.CharField(max_length=255)),
                ('language', models.CharField(default='fr', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='reports.aiconfigsection')),
            ],
            options={
                'db_table': 'ai_synonyms',
                'ordering': ['entity_type', 'canonical_value', 'synonym_value'],
                'constraints': [models.UniqueConstraint(fields=('section', 'entity_type', 'canonical_value', 'synonym_value', 'language'), name='unique_ai_synonym_entry')],
            },
        ),
        migrations.RunPython(seed_ai_config, migrations.RunPython.noop),
    ]
