from django.db import migrations


def seed_enterprise_ai_config(apps, schema_editor):
    AIConfigSection = apps.get_model("reports", "AIConfigSection")
    AIPromptTemplate = apps.get_model("reports", "AIPromptTemplate")
    AIBusinessVocabulary = apps.get_model("reports", "AIBusinessVocabulary")
    AIBusinessRule = apps.get_model("reports", "AIBusinessRule")
    AIVisualMapping = apps.get_model("reports", "AIVisualMapping")
    AIKPITarget = apps.get_model("reports", "AIKPITarget")
    AIRecommendedAction = apps.get_model("reports", "AIRecommendedAction")

    section = AIConfigSection.objects.filter(code="performance").first()
    if not section:
        return

    prompts = [
        (
            "intent_extraction",
            "Default Intent Extraction",
            "You are an intent extraction engine for Mining 360.\n"
            "Convert the user question into a structured JSON intent.\n"
            "Do not answer the question.\n"
            "Return only valid JSON.\n"
            "Use only configured business glossary, synonyms, metrics and filters.\n"
            "Do not generate DAX.\n"
            "Payload:\n{payload_json}",
        ),
        (
            "response_generation",
            "Default Response Generation",
            "You are Mining360 AI, a business assistant for mining operations.\n"
            "Answer in French, clearly and directly.\n"
            "Use only values present in the payload.\n"
            "Do not mention JSON, DAX, prompts, or internal execution.\n"
            "Payload:\n{payload_json}",
        ),
        (
            "business_explanation",
            "Default Business Explanation",
            "Explain the mining business meaning of the result using configured business vocabulary only.\n"
            "Payload:\n{payload_json}",
        ),
        (
            "recommendation",
            "Default Recommendation",
            "Generate concise operational recommendations using configured rules and recommended actions only.\n"
            "Payload:\n{payload_json}",
        ),
        (
            "executive_summary",
            "Default Executive Summary",
            "Create an executive summary for mining leadership using configured metrics, targets and thresholds.\n"
            "Payload:\n{payload_json}",
        ),
        (
            "comparison",
            "Default Comparison",
            "Compare entities or periods using configured metrics and filters only.\n"
            "Payload:\n{payload_json}",
        ),
        (
            "trend_analysis",
            "Default Trend Analysis",
            "Analyze trend direction, weak points and notable changes using configured result data only.\n"
            "Payload:\n{payload_json}",
        ),
    ]
    for prompt_type, name, text in prompts:
        AIPromptTemplate.objects.update_or_create(
            section=section,
            prompt_type=prompt_type,
            template_name=name,
            defaults={
                "prompt_template": text,
                "description": "Seeded editable prompt template.",
                "is_active": True,
            },
        )

    vocabulary = [
        ("Availability", "Percentage of time equipment is available for operation.", "Performance"),
        ("Physical Availability", "Availability adjusted for physical equipment readiness.", "Performance"),
        ("MTBF", "Mean Time Between Failures.", "Reliability"),
        ("MTTR", "Mean Time To Repair.", "Maintainability"),
        ("PCR", "Planned Component Rebuild.", "Maintenance"),
        ("Remaining Useful Life", "Estimated remaining life before a component reaches its expected limit.", "Maintenance"),
        ("VisionLink", "Caterpillar telematics platform for equipment data.", "Systems"),
        ("SOS", "Scheduled Oil Sampling program used to monitor component health.", "Condition Monitoring"),
        ("Operator Events", "Events generated by operator behavior or machine operation.", "Operations"),
        ("Parts Sales", "Revenue or quantity related to parts transactions.", "Commercial"),
    ]
    for term, definition, category in vocabulary:
        AIBusinessVocabulary.objects.update_or_create(
            section=section,
            business_term=term,
            defaults={"business_definition": definition, "category": category, "is_active": True},
        )

    rules = [
        ("availability", "Default period", "If period is missing", "Use current month", "current_month", 10),
        ("availability", "All models", "If model is missing", "Return all models", "", 20),
        ("availability", "Require minesite", "If minesite is missing", "Ask user for minesite", "", 30),
    ]
    for metric, name, condition, action, default_value, priority in rules:
        AIBusinessRule.objects.update_or_create(
            section=section,
            metric_code=metric,
            rule_name=name,
            defaults={
                "condition": condition,
                "action": action,
                "default_value": default_value,
                "priority": priority,
                "is_active": True,
            },
        )

    visuals = [
        ("availability", "Gauge", 10),
        ("availability", "Line Chart", 20),
        ("mtbf", "Trend", 10),
        ("downtime", "Stacked Bar", 10),
    ]
    for metric, visual, priority in visuals:
        AIVisualMapping.objects.update_or_create(
            section=section,
            metric_code=metric,
            recommended_visual=visual,
            defaults={"description": "", "priority": priority, "is_active": True},
        )

    AIKPITarget.objects.update_or_create(
        section=section,
        metric_code="availability",
        defaults={
            "target": "0.90",
            "warning_threshold": "0.85",
            "critical_threshold": "0.80",
            "unit": "%",
            "is_active": True,
        },
    )

    AIRecommendedAction.objects.update_or_create(
        section=section,
        metric_code="availability",
        condition="<85%",
        defaults={
            "recommendations": "Review downtime drivers\nReview repetitive failures\nReview idle events\nReview operator events",
            "priority": 10,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_aidebugrun_aibusinessrule_aifewshotexample_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_enterprise_ai_config, migrations.RunPython.noop),
    ]
