# Generated by Django 6.0.6 on 2026-07-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_aisemanticcolumn_business_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('engine', models.CharField(choices=[('SQL Server', 'SQL Server'), ('Snowflake', 'Snowflake'), ('SQLite', 'SQLite'), ('Other', 'Other')], default='SQL Server', max_length=80)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=255)),
                ('schema_name', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('driver', models.CharField(blank=True, max_length=255)),
                ('connection_options', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=80)),
                ('last_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SystemDatabaseConfig',
                'ordering': ['engine', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemManagedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(default='dbo', max_length=128)),
                ('table_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Django Config', 'Django Config'), ('IA Config', 'IA Config'), ('Knowledge Base', 'Knowledge Base'), ('Data Browser', 'Data Browser'), ('Sources', 'Sources'), ('Resources', 'Resources'), ('Power BI', 'Power BI'), ('Logs', 'Logs'), ('Other', 'Other')], default='Django Config', max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tables', to='reports.systemdatabaseconfig')),
            ],
            options={
                'db_table': 'SystemManagedTable',
                'ordering': ['category', 'schema_name', 'table_name'],
                'constraints': [models.UniqueConstraint(fields=('schema_name', 'table_name'), name='unique_system_managed_table')],
            },
        ),
    ]
