# Generated by Django 6.0.6 on 2026-07-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_business_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmanagedtable',
            name='category',
            field=models.CharField(choices=[('Django Config', 'Django Config'), ('IA Config', 'IA Config'), ('Knowledge Base', 'Knowledge Base'), ('Data Browser', 'Data Browser'), ('Sources', 'Sources'), ('Resources', 'Resources'), ('Power BI', 'Power BI'), ('Business Performance', 'Business Performance'), ('Logs', 'Logs'), ('Other', 'Other')], default='Django Config', max_length=80),
        ),
    ]
