# Generated by Django 6.0.6 on 2026-07-12 23:04

from django.db import migrations


def seed_actions(apps, schema_editor):
    Action = apps.get_model("reports", "SupportedPowerBIAction")
    actions = [
        ("open_report", "Open Report", "report"),
        ("open_page", "Open Page", "page"),
        ("apply_filter", "Apply Filter", "report"),
        ("set_slicer", "Set Slicer", "slicer"),
        ("focus", "Focus Visual", "visual"),
        ("show", "Show Visual", "visual"),
        ("read_filters", "Read Filters", "visual"),
        ("export_data", "Export Data", "visual"),
        ("refresh", "Refresh Report", "report"),
    ]
    for code, name, target in actions:
        Action.objects.get_or_create(
            action_code=code,
            defaults={"display_name": name, "target_type": target, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_supportedpowerbiaction_powerbireport_powerbipage_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_actions, migrations.RunPython.noop),
    ]
