# Generated by Django 6.0.6 on 2026-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_seed_powerbi_interaction_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='ai_usage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='business_category',
            field=models.CharField(choices=[('Reliability', 'Reliability'), ('Maintenance', 'Maintenance'), ('Operations', 'Operations'), ('Productivity', 'Productivity'), ('Fuel', 'Fuel'), ('Parts Sales', 'Parts Sales'), ('Component Rebuild', 'Component Rebuild'), ('Financial', 'Financial'), ('Other', 'Other')], default='Other', max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='business_explanation_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='business_interpretation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='business_owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='business_purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='calculation_type',
            field=models.CharField(choices=[('Ratio', 'Ratio'), ('Percentage', 'Percentage'), ('Sum', 'Sum'), ('Average', 'Average'), ('Weighted Average', 'Weighted Average'), ('Count', 'Count'), ('Duration', 'Duration'), ('Rate', 'Rate'), ('Index', 'Index'), ('Custom', 'Custom')], default='Custom', max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='child_kpis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='clarification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='comparison_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='data_quality_warning_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='decimal_precision',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='default_answer_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='default_comparison_period',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='default_comparison_type',
            field=models.CharField(choices=[('None', 'None'), ('Previous Period', 'Previous Period'), ('Previous Month', 'Previous Month'), ('Previous Year', 'Previous Year'), ('Target', 'Target'), ('Budget', 'Budget'), ('Benchmark', 'Benchmark'), ('Custom', 'Custom')], default='None', max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='default_drill_down_dimension',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='default_ranking_direction',
            field=models.CharField(choices=[('Highest First', 'Highest First'), ('Lowest First', 'Lowest First'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='default_top_n',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='denominator_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='diagnostic_kpis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='display_format',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='forecast_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='freshness_requirement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='higher_is_better',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='lower_is_better',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='minimum_data_completeness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='minimum_equipment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='null_handling_rule',
            field=models.CharField(choices=[('Ignore Nulls', 'Ignore Nulls'), ('Treat as Zero', 'Treat as Zero'), ('Return Blank', 'Return Blank'), ('Use Previous Value', 'Use Previous Value'), ('Custom', 'Custom')], default='Ignore Nulls', max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='numerator_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='optional_filters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='parent_kpi',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='powerbi_measure_full_reference',
            field=models.CharField(blank=True, max_length=520),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='powerbi_measure_table',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='powerbi_report_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='powerbi_semantic_model_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='powerbi_workspace_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='primary_visual_internal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='primary_visual_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='ranking_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='related_kpis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='required_filters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='review_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual'), ('On Change', 'On Change')], default='On Change', max_length=40),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='root_cause_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='source_page_internal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='source_page_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='source_report_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='supported_dimensions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='target_measure_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='target_source',
            field=models.CharField(choices=[('Fixed Value', 'Fixed Value'), ('Power BI Measure', 'Power BI Measure'), ('Site Target', 'Site Target'), ('Customer Target', 'Customer Target'), ('Model Target', 'Model Target'), ('External Benchmark', 'External Benchmark')], default='Fixed Value', max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='technical_owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='threshold_direction',
            field=models.CharField(choices=[('Higher Is Better', 'Higher Is Better'), ('Lower Is Better', 'Lower Is Better')], default='Higher Is Better', max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='threshold_evaluation_rule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='trend_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='version',
            field=models.CharField(default='1.0', max_length=40),
        ),
        migrations.AddField(
            model_name='knowledgekpidictionary',
            name='zero_denominator_behavior',
            field=models.CharField(choices=[('Return Blank', 'Return Blank'), ('Return Zero', 'Return Zero'), ('Return Error', 'Return Error'), ('Custom', 'Custom')], default='Return Blank', max_length=80),
        ),
    ]
