# Generated by Django 6.0.6 on 2026-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_extend_kpi_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLConfigSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=160, unique=True)),
                ('table_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Syncing', 'Syncing'), ('Failed', 'Failed')], default='Pending', max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_sql_config_sync_queue',
                'ordering': ['updated_at', 'model_name'],
            },
        ),
    ]
