# Generated by Django 6.0.6 on 2026-07-17 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_add_sql_config_sync_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mining360 Monthly Budget', max_length=160)),
                ('organization_id', models.CharField(blank=True, max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('warning_percentage', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('critical_percentage', models.DecimalField(decimal_places=2, default=90, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('billing_url', models.URLField(blank=True, default='https://platform.openai.com/settings/organization/billing/credit-grants')),
                ('timezone_name', models.CharField(default='UTC', max_length=80)),
                ('enable_cost_synchronization', models.BooleanField(default=True)),
                ('enable_internal_usage_logging', models.BooleanField(default=True)),
                ('enable_credit_synchronization', models.BooleanField(default=False)),
                ('usage_sync_frequency_minutes', models.PositiveIntegerField(default=60)),
                ('cost_sync_frequency_minutes', models.PositiveIntegerField(default=360)),
                ('data_retention_days', models.PositiveIntegerField(default=730)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'OpenAIBudget',
                'ordering': ['-effective_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpenAICreditSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(blank=True, max_length=120)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('synchronized_at', models.DateTimeField(auto_now=True)),
                ('availability_status', models.CharField(default='Unavailable from API', max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'OpenAICreditSnapshot',
                'ordering': ['-synchronized_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenAICostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('line_item', models.CharField(blank=True, max_length=255)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('synchronized_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'OpenAICostSnapshot',
                'ordering': ['-start_time'],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'project_id', 'start_time', 'end_time', 'line_item', 'currency'), name='unique_openai_cost_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='OpenAIModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=160)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('input_cost_per_million_tokens', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('cached_input_cost_per_million_tokens', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('output_cost_per_million_tokens', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'OpenAIModelPricing',
                'ordering': ['model_name', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('model_name', 'effective_from'), name='unique_openai_model_price_period')],
            },
        ),
        migrations.CreateModel(
            name='OpenAIUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('model', models.CharField(blank=True, db_index=True, max_length=160)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('requests', models.PositiveBigIntegerField(default=0)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('synchronized_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'OpenAIUsageSnapshot',
                'ordering': ['-start_time'],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'project_id', 'model', 'start_time', 'end_time'), name='unique_openai_usage_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='OpenAIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, max_length=120)),
                ('feature', models.CharField(blank=True, db_index=True, max_length=160)),
                ('model', models.CharField(blank=True, db_index=True, max_length=160)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('api_key_id', models.CharField(blank=True, max_length=255)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('official_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='Successful', max_length=40)),
                ('error_code', models.CharField(blank=True, max_length=160)),
                ('environment', models.CharField(db_index=True, default='development', max_length=80)),
                ('usage_timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OpenAIUsageLog',
                'ordering': ['-usage_timestamp'],
                'indexes': [models.Index(fields=['usage_timestamp', 'model'], name='openai_usage_time_model'), models.Index(fields=['usage_timestamp', 'section'], name='openai_usage_time_section')],
            },
        ),
    ]
