# Generated by Django 6.0.6 on 2026-07-18 15:12

import django.db.models.functions.text
from django.db import migrations, models


def remove_case_insensitive_duplicates(apps, schema_editor):
    KnowledgeSynonym = apps.get_model("reports", "KnowledgeSynonym")
    seen = set()
    duplicate_ids = []
    for item in KnowledgeSynonym.objects.order_by("id").iterator():
        key = (
            item.section_id,
            str(item.entity_type or "").casefold(),
            str(item.canonical_term or "").strip().casefold(),
            str(item.synonym or "").strip().casefold(),
        )
        if key in seen:
            duplicate_ids.append(item.id)
        else:
            seen.add(key)
    if duplicate_ids:
        KnowledgeSynonym.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_add_openai_usage_managed_category'),
    ]

    operations = [
        migrations.RunPython(remove_case_insensitive_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='knowledgesynonym',
            constraint=models.UniqueConstraint(models.F('section'), models.F('entity_type'), django.db.models.functions.text.Lower('canonical_term'), django.db.models.functions.text.Lower('synonym'), name='unique_kb_synonym_case_insensitive'),
        ),
    ]
