# Generated by Django 6.0.6 on 2026-07-18 16:23

import django.db.models.deletion
import re
import unicodedata
from django.conf import settings
from django.db import migrations, models


def migrate_existing_synonyms(apps, schema_editor):
    Synonym = apps.get_model("reports", "KnowledgeSynonym")
    for item in Synonym.objects.all().iterator():
        text = unicodedata.normalize("NFKD", str(item.synonym or "").strip().casefold())
        text = "".join(char for char in text if not unicodedata.combining(char))
        text = re.sub(r"[^\w\s+#%./-]", " ", text, flags=re.UNICODE)
        item.normalized_synonym_key = re.sub(r"\s+", " ", text).strip()
        item.normalized_value = str(item.canonical_term or "").strip()
        item.match_type = "Phrase" if len(item.normalized_synonym_key.split()) > 1 else "Exact"
        item.synonym_source = (
            "System Generated"
            if str(item.owner or "") == "Mining360 Browser synchronization"
            else "Manual"
        )
        # Legacy confidence was stored on a 0..1 scale.
        if item.confidence is not None and item.confidence <= 1:
            item.confidence *= 100
        item.save(update_fields=[
            "normalized_synonym_key", "normalized_value", "match_type",
            "synonym_source", "confidence",
        ])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_enforce_unique_synonyms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfigsection",
            name="synonym_ambiguity_threshold",
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.RemoveConstraint(
            model_name='knowledgesynonym',
            name='unique_kb_synonym_case_insensitive',
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='ambiguity_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_synonyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='is_ambiguous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='last_used_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='last_used_question',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='match_type',
            field=models.CharField(choices=[('Exact', 'Exact'), ('Phrase', 'Phrase'), ('Contains', 'Contains'), ('Abbreviation', 'Abbreviation'), ('Fuzzy', 'Fuzzy'), ('Semantic', 'Semantic')], default='Exact', max_length=30),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='normalized_synonym_key',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='normalized_value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='resolution_priority',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='synonym_source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Business', 'Business'), ('Imported', 'Imported'), ('System Generated', 'System Generated'), ('AI Generated', 'AI Generated')], default='Manual', max_length=40),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_knowledge_synonyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='validated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='knowledgesynonym',
            name='validated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_knowledge_synonyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_existing_synonyms, noop_reverse),
        migrations.AddIndex(
            model_name='knowledgesynonym',
            index=models.Index(fields=['section', 'entity_type', 'language', 'normalized_synonym_key'], name='kb_syn_resolve_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesynonym',
            index=models.Index(fields=['section', 'validation_status', 'is_active'], name='kb_syn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesynonym',
            index=models.Index(fields=['canonical_term'], name='kb_syn_canonical_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesynonym',
            index=models.Index(fields=['normalized_value'], name='kb_syn_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesynonym',
            constraint=models.CheckConstraint(condition=models.Q(('usage_count__gte', 0)), name='kb_syn_usage_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesynonym',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 100)), name='kb_syn_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesynonym',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_priority__gte', 1), ('resolution_priority__lte', 100)), name='kb_syn_priority_range'),
        ),
        migrations.AlterField(
            model_name="knowledgesynonym",
            name="confidence",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name="knowledgesynonym",
            name="normalized_value",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="knowledgesynonym",
            name="normalized_synonym_key",
            field=models.CharField(blank=True, db_index=True, default="", editable=False, max_length=255),
        ),
    ]
