# Generated by Django 6.0.6 on 2026-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_extend_synonym_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesynonym',
            name='entity_type',
            field=models.CharField(choices=[('KPI', 'KPI'), ('Filter', 'Filter'), ('Mine Site', 'Mine Site'), ('Model', 'Model'), ('Equipment Family', 'Equipment Family'), ('Serial Number', 'Serial Number'), ('Component', 'Component'), ('Customer', 'Customer'), ('Period', 'Period'), ('Business Term', 'Business Term')], max_length=80),
        ),
    ]
