# Generated by Django 6.0.6 on 2026-07-20 13:06

from django.db import migrations, models


FLEET_SITE_GROUP_MAPPING = {
    "SNIM-Guelb": "SNIM-Guelb",
    "Fekola": "B2Gold Fekola",
    "Agbaou/Mota": "Mota Agbaou",
    "Sangaredi/CBG": "CBG Sangaredi",
    "Essakane": "IAMGOLD Essakane",
    "Simandou/Mota": "Mota Simandou",
    "Seguela": "Mota Seguela",
    "Boto/Mota": "Mota Boto",
    "Siguiri": "AngloGold Ashanti Siguiri",
    "Sabodala": "Sabodala Gold Operations",
    "Tongon": "Corica Tongon",
    "Goulamina/Corica": "Corica Goulamina",
    "Kouroussa": "Corica Kouroussa",
    "Bonikro/Mota": "Mota Bonikro",
    "Sadiola/Mota": "Mota Sadiola",
}


def configure_fleet_site_group(apps, schema_editor):
    PowerBIReport = apps.get_model("reports", "PowerBIReport")
    PowerBIPage = apps.get_model("reports", "PowerBIPage")
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    report = PowerBIReport.objects.filter(
        report_id="6468f0ea-a64d-44b0-8c13-78597ec44bb9",
    ).first()
    if not report:
        return
    page = PowerBIPage.objects.filter(
        report=report,
        page_internal_name="ReportSection3bf2b6e00cab703bd8db",
    ).first()
    if not page:
        return
    PowerBISlicer.objects.update_or_create(
        page=page,
        slicer_internal_name="configured-sitegroup-filter",
        defaults={
            "slicer_title": "SiteGroup",
            "powerbi_table_name": "DIM - Sites",
            "powerbi_column_name": "SiteGroup",
            "filter_code": "minesite",
            "value_mapping": FLEET_SITE_GROUP_MAPPING,
            "data_type": "Text",
            "supports_multiple_values": True,
            "is_required": False,
            "is_active": True,
            "validation_status": "Validated",
        },
    )


def remove_fleet_site_group(apps, schema_editor):
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    PowerBISlicer.objects.filter(
        slicer_internal_name="configured-sitegroup-filter",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_add_availability_filter_entity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbislicer',
            name='value_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(configure_fleet_site_group, remove_fleet_site_group),
    ]
