# Generated by Django 6.0.6 on 2026-07-20 13:22

from django.db import migrations


def configure_monthly_site_labels(apps, schema_editor):
    PowerBIReport = apps.get_model("reports", "PowerBIReport")
    PowerBIPage = apps.get_model("reports", "PowerBIPage")
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    report = PowerBIReport.objects.filter(
        report_id="09299ab4-ba53-4765-8332-20310934b71b",
    ).first()
    if not report:
        return
    page = PowerBIPage.objects.filter(
        report=report,
        page_internal_name="7961ba38d92395517618",
    ).first()
    if not page:
        return
    PowerBISlicer.objects.update_or_create(
        page=page,
        slicer_internal_name="configured-monthly-minesite-filter",
        defaults={
            "slicer_title": "Mine Site",
            "powerbi_table_name": "MineSiteList_MiningProd",
            "powerbi_column_name": "MineSite",
            "filter_code": "minesite",
            "value_mapping": {"Seguela": "Mota Seguela"},
            "data_type": "Text",
            "supports_multiple_values": True,
            "is_required": False,
            "is_active": True,
            "validation_status": "Validated",
        },
    )


def remove_monthly_site_labels(apps, schema_editor):
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    PowerBISlicer.objects.filter(
        slicer_internal_name="configured-monthly-minesite-filter",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_powerbi_slicer_value_mapping'),
    ]

    operations = [
        migrations.RunPython(
            configure_monthly_site_labels,
            remove_monthly_site_labels,
        ),
    ]
