# Generated by Django 6.0.6 on 2026-07-20 13:27

from django.db import migrations


MONTHLY_SITE_GROUP_MAPPING = {
    "SNIM-Guelb": "SNIM-Guelb",
    "Fekola": "B2Gold Fekola",
    "Agbaou/Mota": "Mota Agbaou",
    "Sangaredi/CBG": "CBG Sangaredi",
    "Essakane": "IAMGOLD Essakane",
    "Simandou/Mota": "Mota Simandou",
    "Seguela": "Mota Seguela",
    "Boto/Mota": "Mota Boto",
    "Siguiri": "AngloGold Ashanti Siguiri",
    "Sabodala": "Sabodala Gold Operations",
    "Tongon": "Corica Tongon",
    "Goulamina/Corica": "Corica Goulamina",
    "Kouroussa": "Corica Kouroussa",
    "Bonikro/Mota": "Mota Bonikro",
    "Sadiola/Mota": "Mota Sadiola",
}


def correct_report_site_mappings(apps, schema_editor):
    PowerBIReport = apps.get_model("reports", "PowerBIReport")
    PowerBIPage = apps.get_model("reports", "PowerBIPage")
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")

    PowerBISlicer.objects.filter(
        slicer_internal_name="configured-sitegroup-filter",
        page__report__report_id="6468f0ea-a64d-44b0-8c13-78597ec44bb9",
    ).delete()

    report = PowerBIReport.objects.filter(
        report_id="09299ab4-ba53-4765-8332-20310934b71b",
    ).first()
    if not report:
        return
    page = PowerBIPage.objects.filter(
        report=report,
        page_internal_name="7961ba38d92395517618",
    ).first()
    if not page:
        return
    PowerBISlicer.objects.update_or_create(
        page=page,
        slicer_internal_name="configured-monthly-minesite-filter",
        defaults={
            "slicer_title": "SiteGroup",
            "powerbi_table_name": "DIM - Sites",
            "powerbi_column_name": "SiteGroup",
            "filter_code": "minesite",
            "value_mapping": MONTHLY_SITE_GROUP_MAPPING,
            "data_type": "Text",
            "supports_multiple_values": True,
            "is_required": False,
            "is_active": True,
            "validation_status": "Validated",
        },
    )


def reverse_report_site_mappings(apps, schema_editor):
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    PowerBISlicer.objects.filter(
        slicer_internal_name="configured-monthly-minesite-filter",
    ).update(
        slicer_title="Mine Site",
        powerbi_table_name="MineSiteList_MiningProd",
        powerbi_column_name="MineSite",
        value_mapping={"Seguela": "Mota Seguela"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_configure_monthly_site_labels'),
    ]

    operations = [
        migrations.RunPython(
            correct_report_site_mappings,
            reverse_report_site_mappings,
        ),
    ]
