# Generated by Django 6.0.6 on 2026-07-20 13:34

from django.db import migrations


MONTHLY_SITE_GROUP_MAPPING = {
    "SNIM-Guelb": "SNIM-Guelb",
    "Guelb": "SNIM-Guelb",
    "Fekola": "B2Gold Fekola",
    "B2Gold Fekola": "B2Gold Fekola",
    "Agbaou/Mota": "Mota Agbaou",
    "Agbaou": "Mota Agbaou",
    "Mota Agbaou": "Mota Agbaou",
    "Sangaredi/CBG": "CBG Sangaredi",
    "Sangaredi": "CBG Sangaredi",
    "CBG Sangaredi": "CBG Sangaredi",
    "Essakane": "IAMGOLD Essakane",
    "IAMGOLD Essakane": "IAMGOLD Essakane",
    "Simandou/Mota": "Mota Simandou",
    "Simandou": "Mota Simandou",
    "Mota Simandou": "Mota Simandou",
    "Seguela": "Mota Seguela",
    "Mota Seguela": "Mota Seguela",
    "Boto/Mota": "Mota Boto",
    "Boto": "Mota Boto",
    "Mota Boto": "Mota Boto",
    "Siguiri": "AngloGold Ashanti Siguiri",
    "AngloGold Ashanti Siguiri": "AngloGold Ashanti Siguiri",
    "Sabodala": "Sabodala Gold Operations",
    "Sabodala Gold Operations": "Sabodala Gold Operations",
    "Tongon": "Corica Tongon",
    "Corica Tongon": "Corica Tongon",
    "Goulamina/Corica": "Corica Goulamina",
    "Goulamina": "Corica Goulamina",
    "Corica Goulamina": "Corica Goulamina",
    "Kouroussa": "Corica Kouroussa",
    "Corica Kouroussa": "Corica Kouroussa",
    "Bonikro/Mota": "Mota Bonikro",
    "Bonikro": "Mota Bonikro",
    "Mota Bonikro": "Mota Bonikro",
    "Sadiola/Mota": "Mota Sadiola",
    "Sadiola": "Mota Sadiola",
    "Mota Sadiola": "Mota Sadiola",
}


def complete_monthly_sitegroup_mapping(apps, schema_editor):
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    PowerBISlicer.objects.filter(
        slicer_internal_name="configured-monthly-minesite-filter",
        page__report__report_id="09299ab4-ba53-4765-8332-20310934b71b",
    ).update(value_mapping=MONTHLY_SITE_GROUP_MAPPING)


def restore_exact_dax_mapping(apps, schema_editor):
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    exact_mapping = {
        "SNIM-Guelb": "SNIM-Guelb",
        "Fekola": "B2Gold Fekola",
        "Agbaou/Mota": "Mota Agbaou",
        "Sangaredi/CBG": "CBG Sangaredi",
        "Essakane": "IAMGOLD Essakane",
        "Simandou/Mota": "Mota Simandou",
        "Seguela": "Mota Seguela",
        "Boto/Mota": "Mota Boto",
        "Siguiri": "AngloGold Ashanti Siguiri",
        "Sabodala": "Sabodala Gold Operations",
        "Tongon": "Corica Tongon",
        "Goulamina/Corica": "Corica Goulamina",
        "Kouroussa": "Corica Kouroussa",
        "Bonikro/Mota": "Mota Bonikro",
        "Sadiola/Mota": "Mota Sadiola",
    }
    PowerBISlicer.objects.filter(
        slicer_internal_name="configured-monthly-minesite-filter",
        page__report__report_id="09299ab4-ba53-4765-8332-20310934b71b",
    ).update(value_mapping=exact_mapping)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_correct_report_site_mappings'),
    ]

    operations = [
        migrations.RunPython(
            complete_monthly_sitegroup_mapping,
            restore_exact_dax_mapping,
        ),
    ]
