# Generated by Django 6.0.6 on 2026-07-20 14:00

from django.db import migrations


def configure_fleet_year_month_filter(apps, schema_editor):
    PowerBIReport = apps.get_model("reports", "PowerBIReport")
    PowerBIPage = apps.get_model("reports", "PowerBIPage")
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    report = PowerBIReport.objects.filter(
        report_id="6468f0ea-a64d-44b0-8c13-78597ec44bb9",
    ).first()
    if not report:
        return
    page = PowerBIPage.objects.filter(
        report=report,
        page_internal_name="ReportSection3bf2b6e00cab703bd8db",
    ).first()
    if not page:
        return
    PowerBISlicer.objects.update_or_create(
        page=page,
        slicer_internal_name="configured-fleet-year-month-filter",
        defaults={
            "slicer_title": "Year Month",
            "powerbi_table_name": "Date",
            "powerbi_column_name": "Year Month",
            "filter_code": "period",
            "value_mapping": {},
            "data_type": "Text",
            "supports_multiple_values": True,
            "is_required": False,
            "is_active": True,
            "validation_status": "Validated",
        },
    )


def remove_fleet_year_month_filter(apps, schema_editor):
    PowerBISlicer = apps.get_model("reports", "PowerBISlicer")
    PowerBISlicer.objects.filter(
        slicer_internal_name="configured-fleet-year-month-filter",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_complete_monthly_sitegroup_mapping'),
    ]

    operations = [
        migrations.RunPython(
            configure_fleet_year_month_filter,
            remove_fleet_year_month_filter,
        ),
    ]
