# Generated by Django 6.0.6 on 2026-07-20 14:10

from django.db import migrations
from django.utils import timezone


CBG_ALIASES = (
    ("GBG", "gbg", "Abbreviation", "System Generated"),
    ("CBG Sangaredi", "cbg sangaredi", "Phrase", "Business"),
    ("Sangaredi CBG", "sangaredi cbg", "Phrase", "Business"),
)


def add_cbg_resolution_aliases(apps, schema_editor):
    AIConfigSection = apps.get_model("reports", "AIConfigSection")
    KnowledgeSynonym = apps.get_model("reports", "KnowledgeSynonym")
    section = AIConfigSection.objects.filter(code="performance").first()
    if not section:
        return
    for synonym, normalized_key, match_type, source in CBG_ALIASES:
        KnowledgeSynonym.objects.update_or_create(
            section=section,
            entity_type="Mine Site",
            language="en",
            normalized_synonym_key=normalized_key,
            defaults={
                "canonical_term": "Sangaredi/CBG",
                "synonym": synonym,
                "normalized_value": "Sangaredi/CBG",
                "confidence": 100,
                "synonym_source": source,
                "match_type": match_type,
                "resolution_priority": 100,
                "is_ambiguous": False,
                "ambiguity_notes": (
                    "GBG is accepted as a common typing error for CBG in "
                    "the Mining Performance context."
                    if synonym == "GBG" else ""
                ),
                "validation_status": "Validated",
                "owner": "Mining360 AI",
                "is_active": True,
                "validated_at": timezone.now(),
            },
        )


def remove_cbg_resolution_aliases(apps, schema_editor):
    KnowledgeSynonym = apps.get_model("reports", "KnowledgeSynonym")
    KnowledgeSynonym.objects.filter(
        normalized_synonym_key__in=[item[1] for item in CBG_ALIASES],
        owner="Mining360 AI",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_configure_fleet_year_month_filter'),
    ]

    operations = [
        migrations.RunPython(
            add_cbg_resolution_aliases,
            remove_cbg_resolution_aliases,
        ),
    ]
