# Generated by Django 6.0.6 on 2026-07-20 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_root_cause_configuration(apps, schema_editor):
    Section = apps.get_model("reports", "AIConfigSection")
    Dimension = apps.get_model("reports", "RootCauseDimension")
    Theme = apps.get_model("reports", "RootCauseTheme")
    QualityRule = apps.get_model("reports", "CommentQualityRule")
    RepeatRule = apps.get_model("reports", "RepeatFailureRule")
    DaxTemplate = apps.get_model("reports", "AIDaxTemplate")
    Prompt = apps.get_model("reports", "KnowledgePrompt")

    section = Section.objects.filter(code="performance").first()
    if not section:
        return

    dimensions = [
        ("downtime_driver", "Downtime Driver", "DescriptionCat", 0, 10),
        ("work_type", "Work Type", "WorkType", 1, 20),
        ("labour_type", "Labour Type", "LabourType", 1, 30),
        ("equipment", "Equipment", "Equip", 1, 40),
        ("serial_number", "Serial Number", "SN", 2, 50),
        ("model", "Model", "Model", 1, 60),
    ]
    parents = {}
    for code, display_name, column, level, order in dimensions:
        parent = parents.get("downtime_driver") if level else None
        item, _ = Dimension.objects.update_or_create(
            section=section,
            code=code,
            defaults={
                "display_name": display_name,
                "semantic_table": "DowntimeData_MiningProd",
                "semantic_column": column,
                "parent_dimension": parent,
                "hierarchy_level": level,
                "sort_order": order,
                "entity_type": "Downtime",
                "is_filterable": True,
                "is_clickable": True,
                "available_for_breakdown": code not in {"serial_number"},
                "available_for_comments": True,
                "available_for_repetition_analysis": True,
                "is_active": True,
                "validation_status": "Validated",
            },
        )
        parents[code] = item

    theme_names = [
        "Parts Availability",
        "Technician Availability",
        "Workshop Capacity",
        "Maintenance Planning",
        "Production Constraint",
        "Diagnostic Delay",
        "External Specialist Required",
        "Logistics Delay",
        "Procurement Delay",
        "Rework",
        "Repeat Failure",
        "Incorrect Troubleshooting",
        "Component Failure",
        "Operational Damage",
        "Accident",
        "Incomplete Information",
        "Other",
    ]
    for name in theme_names:
        Theme.objects.update_or_create(
            section=section,
            code=name.lower().replace(" ", "_"),
            defaults={
                "name": name,
                "description": "Business-provided root cause theme.",
                "is_active": True,
                "validation_status": "Validated",
            },
        )

    quality_rules = [
        ("empty", "Empty comment", "Empty", 0, []),
        ("generic", "Generic comment", "Generic", 1, ["machine down", "down", "stopped"]),
        ("low", "Low quality comment", "Low Quality", 20, []),
        ("medium", "Medium quality comment", "Medium Quality", 60, []),
        ("high", "High quality comment", "High Quality", 120, []),
    ]
    for code, name, classification, minimum_length, phrases in quality_rules:
        QualityRule.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "classification": classification,
                "minimum_length": minimum_length,
                "generic_phrases": phrases,
                "priority": minimum_length,
                "is_active": True,
                "validation_status": "Validated",
            },
        )
    RepeatRule.objects.update_or_create(
        name="Equipment Driver Work Type Repeat",
        defaults={
            "dimension_codes": ["serial_number", "downtime_driver", "work_type"],
            "window_days": 90,
            "minimum_occurrences": 2,
            "description": (
                "Same serial number, downtime driver and work type occurring "
                "at least twice within 90 days."
            ),
            "is_active": True,
            "validation_status": "Validated",
        },
    )

    templates = {
        "DOWNTIME_DRIVER_SUMMARY": "Controlled driver summary using {filters} and {driver_filter}.",
        "DOWNTIME_BREAKDOWN_BY_DIMENSION": "Controlled breakdown of {dimension} using {filters}.",
        "DOWNTIME_AFFECTED_EQUIPMENT": "Controlled equipment aggregation using {filters}.",
        "DOWNTIME_EVENT_LIST": "Controlled event list using {filters} and {limit}.",
        "DOWNTIME_COMMENT_EVENTS": "Controlled commented event list using {filters} and {limit}.",
        "DOWNTIME_REPEAT_PATTERN": "Server-side repeat detection over controlled event results.",
        "DOWNTIME_PERIOD_COMPARISON": "Controlled current and previous period comparison.",
        "DOWNTIME_TREND": "Controlled downtime trend by configured period.",
    }
    for code, text in templates.items():
        DaxTemplate.objects.update_or_create(
            section=section,
            template_code=code,
            defaults={
                "template_name": code.replace("_", " ").title(),
                "dax_template": text,
                "description": (
                    "Validated registry entry. Runtime DAX is generated only "
                    "from configured semantic objects."
                ),
                "is_active": True,
            },
        )

    Prompt.objects.update_or_create(
        section=section,
        prompt_name="Downtime Root Cause Comment Analysis",
        defaults={
            "prompt_type": "Root Cause Analysis",
            "prompt_content": (
                "Analyze only the supplied downtime event comments. Return strict JSON. "
                "Never invent a cause. Distinguish Explicitly stated in comments, "
                "Inferred from multiple comments, Potential hypothesis, and Insufficient "
                "information. Every theme must include evidence event IDs, event count, "
                "downtime hours, affected equipment and confidence. Report coverage and "
                "limitations. Use only configured root cause themes supplied in the payload."
            ),
            "version": "1.0",
            "created_by": "System",
            "validation_status": "Validated",
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_configure_availability_downtime_diagnostics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentQualityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=80)),
                ('minimum_length', models.PositiveIntegerField(default=0)),
                ('generic_phrases', models.JSONField(blank=True, default=list)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Deprecated', 'Deprecated')], default='To Review', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_comment_quality_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepeatFailureRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dimension_codes', models.JSONField(default=list)),
                ('window_days', models.PositiveIntegerField(default=90)),
                ('minimum_occurrences', models.PositiveIntegerField(default=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Deprecated', 'Deprecated')], default='To Review', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_repeat_failure_rules',
                'ordering': ['window_days', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeExplorerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_model_name', models.CharField(default='FPR Global DB + RLS', max_length=255)),
                ('semantic_model_id', models.CharField(blank=True, max_length=128)),
                ('source_question', models.TextField(blank=True)),
                ('kpi', models.CharField(default='availability', max_length=120)),
                ('context_json', models.JSONField(default=dict)),
                ('context_hash', models.CharField(db_index=True, max_length=64)),
                ('selected_driver', models.CharField(max_length=255)),
                ('selected_subcategory', models.CharField(blank=True, max_length=255)),
                ('selected_component', models.CharField(blank=True, max_length=255)),
                ('selected_subcomponent', models.CharField(blank=True, max_length=255)),
                ('selected_cause', models.CharField(blank=True, max_length=255)),
                ('current_level', models.CharField(default='overview', max_length=80)),
                ('navigation_stack', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Failed', 'Failed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_explorer_sessions', to='reports.aiconversationcontext')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_explorer_sessions', to='reports.powerbireport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_explorer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_downtime_explorer_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeExplorerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(max_length=80)),
                ('selected_entity_type', models.CharField(blank=True, max_length=120)),
                ('selected_value', models.CharField(blank=True, max_length=500)),
                ('previous_context', models.JSONField(blank=True, default=dict)),
                ('new_context', models.JSONField(blank=True, default=dict)),
                ('query_execution_id', models.CharField(blank=True, max_length=128)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='reports.downtimeexplorersession')),
            ],
            options={
                'db_table': 'ai_downtime_explorer_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeExplorerAIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_json', models.JSONField(default=dict)),
                ('event_ids', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='1.0', max_length=40)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='Completed', max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='reports.downtimeexplorersession')),
            ],
            options={
                'db_table': 'ai_downtime_explorer_ai_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RootCauseDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120)),
                ('display_name', models.CharField(max_length=255)),
                ('semantic_table', models.CharField(max_length=255)),
                ('semantic_column', models.CharField(max_length=255)),
                ('hierarchy_level', models.PositiveSmallIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('entity_type', models.CharField(default='Downtime', max_length=120)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_clickable', models.BooleanField(default=True)),
                ('available_for_breakdown', models.BooleanField(default=True)),
                ('available_for_comments', models.BooleanField(default=True)),
                ('available_for_repetition_analysis', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Deprecated', 'Deprecated')], default='To Review', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_dimensions', to='reports.rootcausedimension')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_dimensions', to='reports.aiconfigsection')),
            ],
            options={
                'db_table': 'ai_root_cause_dimensions',
                'ordering': ['section', 'sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='RootCauseTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Deprecated', 'Deprecated')], default='To Review', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_themes', to='reports.aiconfigsection')),
            ],
            options={
                'db_table': 'ai_root_cause_themes',
                'ordering': ['section', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='downtimeexplorersession',
            index=models.Index(fields=['user', 'context_hash', 'status'], name='dt_explorer_context_idx'),
        ),
        migrations.AddConstraint(
            model_name='rootcausedimension',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='unique_root_cause_dimension_code'),
        ),
        migrations.AddConstraint(
            model_name='rootcausetheme',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='unique_root_cause_theme_code'),
        ),
        migrations.RunPython(seed_root_cause_configuration, migrations.RunPython.noop),
    ]
