# Generated by Django 6.0.6 on 2026-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_downtime_root_cause_explorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMCSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.CharField(db_index=True, max_length=500)),
                ('source', models.CharField(default='CAT SMCS Codes', max_length=120)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Deprecated', 'Deprecated')], default='To Review', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_smcs_codes',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active', 'validation_status'], name='smcs_active_status_idx')],
            },
        ),
    ]
