# Generated by Django 6.0.6 on 2026-07-21 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


SMCS_PROMPT = """You are a mining equipment maintenance classification assistant.
Classify one downtime event comment against the supplied approved Caterpillar SMCS candidates.
Select only a code present in candidate_smcs_codes. Never create, modify or guess a code.
Distinguish symptom, root cause, failed component, inspected component, maintenance action,
delay reason and secondary component mention. Handle negations such as no issue found,
no defect, found OK and ruled out. Prefer a component directly confirmed as defective,
repaired or replaced. If evidence is ambiguous, generic or insufficient, return unresolved.
Evidence phrases must be short verbatim excerpts from the supplied comment.
Return strict JSON matching the requested classification schema only."""


def seed_smcs_preview(apps, schema_editor):
    SMCSCode = apps.get_model('reports', 'SMCSCode')
    SMCSConfig = apps.get_model('reports', 'SMCSClassificationConfig')
    Section = apps.get_model('reports', 'AIConfigSection')
    Prompt = apps.get_model('reports', 'KnowledgePrompt')
    for item in SMCSCode.objects.all().iterator():
        changed = []
        if not item.display_name:
            item.display_name = item.description
            changed.append('display_name')
        if not item.component:
            item.component = item.description
            changed.append('component')
        if changed:
            item.save(update_fields=changed)
    SMCSConfig.objects.update_or_create(
        name='Default',
        defaults={
            'execution_mode': 'Preview',
            'auto_accept_threshold': 85,
            'review_threshold': 70,
            'candidate_score_gap': 10,
            'max_candidates': 12,
            'default_batch_size': 12,
            'prompt_code': 'SMCS_COMMENT_CLASSIFICATION_V1',
            'prompt_version': '1.0',
            'config_version': '1.0',
            'generic_comments_json': [
                'Machine down', 'Still down', 'In progress', 'Under repair',
                'Breakdown', 'Waiting', 'Done',
            ],
            'is_active': True,
        },
    )
    section = Section.objects.filter(code='performance').first()
    if section:
        Prompt.objects.update_or_create(
            section=section,
            prompt_name='SMCS_COMMENT_CLASSIFICATION_V1',
            defaults={
                'prompt_type': 'Root Cause Analysis',
                'prompt_content': SMCS_PROMPT,
                'version': '1.0',
                'created_by': 'System',
                'validation_status': 'Validated',
                'owner': 'Mining 360 AI',
                'is_active': True,
            },
        )


def unseed_smcs_preview(apps, schema_editor):
    apps.get_model('reports', 'KnowledgePrompt').objects.filter(
        prompt_name='SMCS_COMMENT_CLASSIFICATION_V1',
        created_by='System',
    ).delete()
    apps.get_model('reports', 'SMCSClassificationConfig').objects.filter(
        name='Default',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_add_smcs_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMCSClassificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=120, unique=True)),
                ('execution_mode', models.CharField(choices=[('Disabled', 'Disabled'), ('Preview', 'Preview'), ('Admin Only', 'Admin Only'), ('Production', 'Production')], default='Preview', max_length=20)),
                ('auto_accept_threshold', models.PositiveSmallIntegerField(default=85)),
                ('review_threshold', models.PositiveSmallIntegerField(default=70)),
                ('candidate_score_gap', models.PositiveSmallIntegerField(default=10)),
                ('max_candidates', models.PositiveSmallIntegerField(default=12)),
                ('default_batch_size', models.PositiveSmallIntegerField(default=12)),
                ('prompt_code', models.CharField(default='SMCS_COMMENT_CLASSIFICATION_V1', max_length=120)),
                ('prompt_version', models.CharField(default='1.0', max_length=40)),
                ('config_version', models.CharField(default='1.0', max_length=40)),
                ('generic_comments_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_smcs_classification_config',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='smcscode',
            name='applicable_models_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='common_field_expressions_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='component',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='display_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='equipment_family',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='exclusion_terms_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='hierarchy_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='keywords_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='reports.smcscode'),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='reference_version',
            field=models.CharField(default='1.0', max_length=40),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='subcomponent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='synonyms_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='smcscode',
            name='system',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SMCSClassificationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='Preview', max_length=20)),
                ('scope', models.CharField(default='unmatched', max_length=40)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Partially Completed', 'Partially Completed'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('processed_events', models.PositiveIntegerField(default=0)),
                ('matched_events', models.PositiveIntegerField(default=0)),
                ('probable_events', models.PositiveIntegerField(default=0)),
                ('unresolved_events', models.PositiveIntegerField(default=0)),
                ('failed_events', models.PositiveIntegerField(default=0)),
                ('deterministic_matches', models.PositiveIntegerField(default=0)),
                ('ai_matches', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('explorer_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smcs_classification_jobs', to='reports.downtimeexplorersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smcs_classification_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_smcs_classification_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeSMCSClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('event_external_id', models.CharField(db_index=True, max_length=160)),
                ('semantic_model', models.CharField(blank=True, max_length=255)),
                ('source_system', models.CharField(default='Power BI', max_length=120)),
                ('comment_hash', models.CharField(db_index=True, max_length=64)),
                ('comment_snapshot', models.TextField(blank=True)),
                ('normalized_comment', models.TextField(blank=True)),
                ('minesite', models.CharField(blank=True, max_length=255)),
                ('equipment_id', models.CharField(blank=True, max_length=160)),
                ('serial_number', models.CharField(blank=True, max_length=160)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('equipment_family', models.CharField(blank=True, max_length=255)),
                ('downtime_driver', models.CharField(blank=True, max_length=255)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('downtime_hours', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('smcs_code_snapshot', models.CharField(blank=True, max_length=20)),
                ('smcs_description_snapshot', models.CharField(blank=True, max_length=500)),
                ('system', models.CharField(blank=True, max_length=255)),
                ('component', models.CharField(blank=True, max_length=255)),
                ('subcomponent', models.CharField(blank=True, max_length=255)),
                ('classification_status', models.CharField(choices=[('matched', 'Matched'), ('probable', 'Probable'), ('unresolved', 'Unresolved'), ('failed_validation', 'Failed Validation')], default='unresolved', max_length=30)),
                ('match_method', models.CharField(choices=[('Explicit SMCS Code', 'Explicit SMCS Code'), ('Exact Description', 'Exact Description'), ('Synonym Match', 'Synonym Match'), ('AI Semantic Classification', 'AI Semantic Classification'), ('Manual Validation', 'Manual Validation'), ('Unresolved', 'Unresolved')], default='Unresolved', max_length=40)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('requires_review', models.BooleanField(default=True)),
                ('review_reason', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('evidence_phrases_json', models.JSONField(blank=True, default=list)),
                ('secondary_mentions_json', models.JSONField(blank=True, default=list)),
                ('alternative_candidates_json', models.JSONField(blank=True, default=list)),
                ('detected_symptoms_json', models.JSONField(blank=True, default=list)),
                ('detected_causes_json', models.JSONField(blank=True, default=list)),
                ('detected_actions_json', models.JSONField(blank=True, default=list)),
                ('detected_delays_json', models.JSONField(blank=True, default=list)),
                ('candidate_list_json', models.JSONField(blank=True, default=list)),
                ('prompt_code', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('config_version', models.CharField(blank=True, max_length=40)),
                ('openai_model', models.CharField(blank=True, max_length=120)),
                ('openai_request_id', models.CharField(blank=True, max_length=160)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('processing_duration_ms', models.PositiveIntegerField(default=0)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Deprecated', 'Deprecated')], default='To Review', max_length=40)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('manual_override', models.BooleanField(default=False)),
                ('manual_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smcs_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtime_classifications', to='reports.smcscode')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_smcs_classifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_downtime_smcs_classifications',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['classification_status', 'requires_review'], name='smcs_class_review_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMCSSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=500)),
                ('normalized_synonym', models.CharField(db_index=True, max_length=500)),
                ('language', models.CharField(default='en', max_length=12)),
                ('synonym_type', models.CharField(choices=[('Official Alias', 'Official Alias'), ('Field Expression', 'Field Expression'), ('Abbreviation', 'Abbreviation'), ('Spelling Variant', 'Spelling Variant'), ('Imported', 'Imported'), ('AI Suggested', 'AI Suggested'), ('Manual', 'Manual')], default='Manual', max_length=40)),
                ('source', models.CharField(default='Manual', max_length=120)),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Deprecated', 'Deprecated')], default='To Review', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smcs_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smcs_synonyms', to='reports.smcscode')),
            ],
            options={
                'db_table': 'ai_smcs_synonyms',
                'ordering': ['smcs_reference__code', 'synonym'],
                'constraints': [models.UniqueConstraint(fields=('smcs_reference', 'language', 'normalized_synonym'), name='unique_smcs_synonym_key')],
            },
        ),
        migrations.RunPython(seed_smcs_preview, unseed_smcs_preview),
    ]
