# Generated by Django 6.0.6 on 2026-07-22 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_seed_gpt56_sol_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperuserWebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=1024, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('device_name', models.CharField(default='Windows Hello', max_length=255)),
                ('aaguid', models.CharField(blank=True, max_length=64)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('device_type', models.CharField(blank=True, max_length=80)),
                ('backed_up', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining360_webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SuperuserWebAuthnCredential',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=160)),
                ('target', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Succeeded', 'Succeeded'), ('Denied', 'Denied'), ('Failed', 'Failed')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.superuserwebauthncredential')),
            ],
            options={
                'db_table': 'SecurityAuditEvent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='superuserwebauthncredential',
            index=models.Index(fields=['user', 'is_active'], name='superuser_webauthn_user_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditevent',
            index=models.Index(fields=['user', 'created_at'], name='security_audit_user_idx'),
        ),
    ]
