# Generated by Django 6.0.6 on 2026-07-22 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_superuser_webauthn_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuserwebauthncredential',
            name='device_name',
            field=models.CharField(default='Platform authenticator', max_length=255),
        ),
        migrations.CreateModel(
            name='SuperuserFaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_reference_image', models.TextField()),
                ('reference_image_hash', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(default='Azure Face', max_length=80)),
                ('provider_model_version', models.CharField(blank=True, max_length=80)),
                ('validation_status', models.CharField(db_index=True, default='Validated', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mining360_face_profile', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_mining360_face_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SuperuserFaceProfile',
            },
        ),
        migrations.CreateModel(
            name='FaceVerificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('Enroll', 'Enroll'), ('Verify', 'Verify')], max_length=20)),
                ('protected_action', models.CharField(blank=True, max_length=160)),
                ('provider', models.CharField(default='Azure Face', max_length=80)),
                ('provider_session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Succeeded', 'Succeeded'), ('Denied', 'Denied'), ('Failed', 'Failed'), ('Expired', 'Expired')], db_index=True, default='Pending', max_length=20)),
                ('liveness_decision', models.CharField(blank=True, max_length=40)),
                ('face_identical', models.BooleanField(blank=True, null=True)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('provider_model_version', models.CharField(blank=True, max_length=80)),
                ('error_code', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FaceVerificationAttempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='face_attempt_user_idx')],
            },
        ),
    ]
