# Generated by Django 6.0.6 on 2026-07-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_superuser_face_identity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='faceverificationattempt',
            name='face_attempt_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityauditevent',
            name='security_audit_user_idx',
        ),
        migrations.RemoveField(
            model_name='superuserfaceprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='superuserfaceprofile',
            name='validated_by',
        ),
        migrations.RemoveIndex(
            model_name='superuserwebauthncredential',
            name='superuser_webauthn_user_idx',
        ),
        migrations.RemoveField(
            model_name='faceverificationattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='securityauditevent',
            name='credential',
        ),
        migrations.RemoveField(
            model_name='securityauditevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='SuperuserFaceProfile',
        ),
        migrations.RemoveField(
            model_name='superuserwebauthncredential',
            name='user',
        ),
        migrations.DeleteModel(
            name='FaceVerificationAttempt',
        ),
        migrations.DeleteModel(
            name='SecurityAuditEvent',
        ),
        migrations.DeleteModel(
            name='SuperuserWebAuthnCredential',
        ),
    ]
