# Generated by Django 6.0.6 on 2026-07-22 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0041_remove_biometric_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('integration_type', models.CharField(choices=[('Power BI', 'Power BI'), ('Power Automate', 'Power Automate'), ('OpenAI', 'OpenAI'), ('Database', 'Database'), ('Data Source', 'Data Source'), ('Storage', 'Storage'), ('Authentication', 'Authentication'), ('Notification', 'Notification'), ('Other', 'Other')], max_length=40)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('encrypted_secrets', models.TextField(blank=True)),
                ('configured_secret_keys', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Not Configured', 'Not Configured'), ('Configured', 'Configured'), ('Connected', 'Connected'), ('Failed', 'Failed'), ('Disabled', 'Disabled')], default='Not Configured', max_length=30)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_integrations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SystemIntegrationConfig',
                'ordering': ['integration_type', 'name'],
                'indexes': [models.Index(fields=['integration_type', 'is_active'], name='system_integration_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Decimal', 'Decimal'), ('Boolean', 'Boolean'), ('JSON', 'JSON'), ('URL', 'URL'), ('Duration', 'Duration')], default='Text', max_length=20)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('default_value_json', models.JSONField(blank=True, null=True)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_runtime_editable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_pattern', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_parameters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_parameters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SystemParameter',
                'ordering': ['category', 'label'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='system_parameter_cat_idx')],
            },
        ),
    ]
