# Generated by Django 6.0.6 on 2026-07-26 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_voice_input'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceKnowledgeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Best Practices Bootstrap', max_length=120, unique=True)),
                ('maximum_chunk_tokens', models.PositiveIntegerField(default=1500)),
                ('minimum_chunk_tokens', models.PositiveIntegerField(default=150)),
                ('chunk_overlap_tokens', models.PositiveIntegerField(default=150)),
                ('preserve_tables', models.BooleanField(default=True)),
                ('preserve_lists', models.BooleanField(default=True)),
                ('preserve_heading_context', models.BooleanField(default=True)),
                ('enable_resource_ocr', models.BooleanField(default=False)),
                ('embedding_mode', models.CharField(choices=[('Disabled', 'Disabled'), ('Local', 'Local'), ('On Demand', 'On Demand'), ('Batch Controlled', 'Batch Controlled')], default='Disabled', max_length=30)),
                ('parser_config_version', models.CharField(default='1', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ResourceKnowledgeConfiguration',
            },
        ),
        migrations.AddField(
            model_name='resourceknowledgechunk',
            name='chunk_type',
            field=models.CharField(db_index=True, default='Text', max_length=30),
        ),
        migrations.AddField(
            model_name='resourceknowledgechunk',
            name='embedding_status',
            field=models.CharField(db_index=True, default='Disabled', max_length=30),
        ),
        migrations.AddField(
            model_name='resourceknowledgechunk',
            name='heading_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resourceknowledgechunk',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=12),
        ),
        migrations.AddField(
            model_name='resourceknowledgechunk',
            name='normalized_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceknowledgechunk',
            name='source_reference',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='resourceknowledgechunk',
            name='validation_status',
            field=models.CharField(db_index=True, default='To Review', max_length=20),
        ),
        migrations.AddField(
            model_name='resourceknowledgedocument',
            name='image_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceknowledgedocument',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=12),
        ),
        migrations.AddField(
            model_name='resourceknowledgedocument',
            name='parser_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='resourceknowledgedocument',
            name='parser_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='resourceknowledgedocument',
            name='processing_config_version',
            field=models.CharField(default='1', max_length=40),
        ),
        migrations.AddField(
            model_name='resourceknowledgedocument',
            name='section_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceknowledgedocument',
            name='table_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceknowledgedocument',
            name='validation_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Superseded', 'Superseded')], db_index=True, default='To Review', max_length=20),
        ),
        migrations.CreateModel(
            name='KnowledgeEnrichmentQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_section', models.CharField(blank=True, max_length=255)),
                ('enrichment_type', models.CharField(choices=[('Document Summary', 'Document Summary'), ('Glossary Extraction', 'Glossary Extraction'), ('Business Rule Extraction', 'Business Rule Extraction'), ('Recommended Action Extraction', 'Recommended Action Extraction'), ('Question Generation', 'Question Generation'), ('Few Shot Generation', 'Few Shot Generation'), ('Embedding Generation', 'Embedding Generation'), ('Image Analysis', 'Image Analysis'), ('OCR', 'OCR')], max_length=80)),
                ('status', models.CharField(db_index=True, default='Pending Approval', max_length=30)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('estimated_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('actual_tokens', models.PositiveIntegerField(default=0)),
                ('actual_cost', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_requests', to='reports.resourceknowledgedocument')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_knowledge_enrichments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_enrichments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'KnowledgeEnrichmentQueue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceKnowledgeConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=1000)),
                ('conflict_description', models.TextField()),
                ('status', models.CharField(db_index=True, default='Open', max_length=30)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_source_a', to='reports.resourceknowledgeitem')),
                ('source_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_source_b', to='reports.resourceknowledgeitem')),
            ],
            options={
                'db_table': 'ResourceKnowledgeConflict',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceKnowledgeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('section_number', models.CharField(blank=True, max_length=80)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('normalized_content', models.TextField(blank=True)),
                ('validation_status', models.CharField(db_index=True, default='To Review', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.resourceknowledgedocument')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='reports.resourceknowledgesection')),
            ],
            options={
                'db_table': 'ResourceKnowledgeSection',
                'ordering': ['document', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='resourceknowledgechunk',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='reports.resourceknowledgesection'),
        ),
        migrations.AddConstraint(
            model_name='resourceknowledgesection',
            constraint=models.UniqueConstraint(fields=('document', 'sort_order'), name='unique_resource_kb_section_order'),
        ),
    ]
