# Generated by Django 6.0.6 on 2026-07-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0047_ai_provider_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='databrowser',
            name='allow_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='allow_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='allow_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='allow_export',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='allow_import',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='default_page_size',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='default_sort_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='external_form_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='maximum_page_size',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='migration_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('read_only', 'Read Only Validation'), ('write_validation', 'Write Validation'), ('ready', 'Ready for Cutover'), ('migrated', 'Migrated'), ('blocked', 'Blocked')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='primary_key_column',
            field=models.CharField(default='BrowserRecordId', max_length=128),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='section',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='source_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_browsers', to='reports.systemintegrationconfig'),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='source_metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='source_mode',
            field=models.CharField(choices=[('managed_table', 'Mining 360 Managed Table'), ('external_view', 'External Database View'), ('miningprod_metaform', 'MiningProd MetaForm')], default='managed_table', max_length=30),
        ),
        migrations.AddField(
            model_name='databrowser',
            name='write_strategy',
            field=models.CharField(choices=[('managed_table', 'Mining 360 Managed Table'), ('read_only', 'Read Only'), ('miningprod_metaform', 'MiningProd MetaForm Service')], default='managed_table', max_length=30),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='is_exportable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='is_filterable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='is_sortable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='source_column_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='source_field_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databrowsercolumn',
            name='source_metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
