# Generated by Django 6.0.6 on 2026-07-30 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0048_miningprod_data_browser_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBrowserWriteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('direct_table', 'Direct Table'), ('eventchain_eav', 'EventChain EAV'), ('metaform_adapter', 'MetaForm Adapter')], max_length=30)),
                ('root_table', models.CharField(max_length=128)),
                ('root_primary_key', models.CharField(max_length=128)),
                ('configuration_json', models.JSONField(blank=True, default=dict)),
                ('mapping_version', models.CharField(default='1.0', max_length=30)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('preview_validated', 'Preview Validated'), ('write_validated', 'Write Validated'), ('active', 'Active'), ('blocked', 'Blocked')], default='draft', max_length=30)),
                ('allow_create', models.BooleanField(default=False)),
                ('allow_edit', models.BooleanField(default=False)),
                ('allow_delete', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('preview_validated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_browser_mappings', to=settings.AUTH_USER_MODEL)),
                ('browser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='write_mapping', to='reports.databrowser')),
                ('preview_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_validated_browser_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DataBrowserWriteMapping',
                'ordering': ['browser__display_order', 'browser__name'],
            },
        ),
        migrations.CreateModel(
            name='MiningProdUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.PositiveIntegerField(unique=True)),
                ('external_username', models.CharField(max_length=150)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='miningprod_user_mapping', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_miningprod_user_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MiningProdUserMapping',
                'ordering': ['external_username'],
            },
        ),
        migrations.CreateModel(
            name='DataBrowserWriteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('record_key', models.CharField(blank=True, max_length=255)),
                ('input_hash', models.CharField(max_length=64)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('execution_plan_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('validated', 'Validated'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='previewed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_audit_logs', to='reports.databrowser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_browser_write_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='reports.databrowserwritemapping')),
            ],
            options={
                'db_table': 'DataBrowserWriteAuditLog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['browser', 'operation', 'created_at'], name='browser_write_audit_idx')],
            },
        ),
    ]
