# Generated by Django 6.0.6 on 2026-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0049_miningprod_browser_write_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningprodusermapping',
            name='external_employee_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='miningprodusermapping',
            name='external_user_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='miningprodusermapping',
            name='external_username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
