# Generated by Django 6.0.6 on 2026-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_miningprod_user_identity_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databrowserwriteauditlog',
            name='operation',
            field=models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('rollback_test', 'Rollback Test')], max_length=20),
        ),
    ]
