# Generated by Django 6.0.6 on 2026-08-07 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0053_allow_json_scalars_in_system_parameters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New conversation', max_length=200)),
                ('title_is_manual', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('active_agent_code', models.CharField(blank=True, max_length=100)),
                ('last_agent_code', models.CharField(blank=True, max_length=100)),
                ('conversation_context_json', models.JSONField(blank=True, default=dict)),
                ('performance_context_json', models.JSONField(blank=True, default=dict)),
                ('knowledge_context_json', models.JSONField(blank=True, default=dict)),
                ('active_analysis_json', models.JSONField(blank=True, default=dict)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=30)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('content', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('agent_code', models.CharField(blank=True, max_length=100)),
                ('intent_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('client_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports.aiconversation')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_versions', to='reports.aiconversationmessage')),
            ],
            options={
                'db_table': 'ai_conversation_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIConversationArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('source_type', models.CharField(blank=True, max_length=80)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('failed', 'Failed')], default='active', max_length=20)),
                ('artifact_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='reports.aiconversation')),
                ('supersedes_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='reports.aiconversationartifact')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='reports.aiconversationmessage')),
            ],
            options={
                'db_table': 'ai_conversation_artifacts',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'status', '-last_message_at'], name='ai_conv_user_status_activity'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['conversation', '-created_at'], name='ai_msg_conv_created'),
        ),
        migrations.AddConstraint(
            model_name='aiconversationmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('conversation', 'client_message_id'), name='unique_ai_client_message_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='aiconversationartifact',
            index=models.Index(fields=['conversation', 'message'], name='ai_art_conv_message'),
        ),
        migrations.AddIndex(
            model_name='aiconversationartifact',
            index=models.Index(fields=['conversation', 'artifact_type'], name='ai_art_conv_type'),
        ),
    ]
