# Generated by Django 6.0.6 on 2026-08-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0054_persistent_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationartifact',
            name='refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
