# Generated by Django 6.0.6 on 2026-08-08 16:36

import django.db.models.deletion
from django.db import migrations, models


TEMPLATES = {
    'single_kpi': ['primary_metric', 'context', 'contextual_actions'],
    'performance_overview': ['metric_grid', 'key_takeaway', 'contextual_actions'],
    'equipment_detail': ['equipment_identity', 'metric_grid', 'result_table', 'contextual_actions'],
    'downtime_drivers': ['context', 'downtime_summary', 'key_takeaway', 'downtime_drivers', 'contextual_actions'],
    'entity_comparison': ['context', 'comparison_summary', 'comparison_table', 'key_takeaway', 'contextual_actions'],
    'period_comparison': ['context', 'comparison_summary', 'comparison_table', 'key_takeaway', 'contextual_actions'],
    'trend_analysis': ['context', 'trend_summary', 'trend_chart', 'result_table', 'contextual_actions'],
    'ranking': ['context', 'ranking_table', 'key_takeaway', 'contextual_actions'],
    'affected_equipment': ['context', 'equipment_table', 'contextual_actions'],
    'downtime_events': ['context', 'events_table', 'contextual_actions'],
    'root_cause_analysis': ['context', 'diagnostic_summary', 'downtime_drivers', 'evidence', 'contextual_actions'],
    'repeated_failures': ['context', 'repeated_failures', 'result_table', 'contextual_actions'],
    'comment_analysis': ['context', 'comment_coverage', 'evidence', 'result_table', 'contextual_actions'],
    'smcs_breakdown': ['context', 'smcs_coverage', 'result_table', 'contextual_actions'],
    'powerbi_navigation': ['navigation_confirmation', 'contextual_actions'],
    'generic_analytical': ['context', 'result_table', 'contextual_actions'],
    'legacy_availability_response': ['primary_metric', 'context', 'downtime_summary', 'downtime_drivers', 'contextual_actions'],
}

REQUIRED_DATA = {
    'single_kpi': ['metric_value'], 'entity_comparison': ['multiple_rows'],
    'period_comparison': ['multiple_rows'], 'trend_analysis': ['multiple_rows'],
    'ranking': ['rows'], 'downtime_drivers': ['downtime_drivers'],
    'equipment_detail': ['equipment_identity'],
}


def seed_templates(apps, schema_editor):
    Template = apps.get_model('reports', 'AIResponseTemplate')
    Mapping = apps.get_model('reports', 'AIIntentResponseTemplateMapping')
    for code, components in TEMPLATES.items():
        template, _ = Template.objects.update_or_create(
            code=code,
            defaults={
                'name': code.replace('_', ' ').title(),
                'domain': 'machine_performance',
                'supported_intent_types': [code],
                'primary_component': components[0],
                'component_order_json': components,
                'required_data_fields_json': REQUIRED_DATA.get(code, []),
                'fallback_template_code': 'generic_analytical' if code != 'generic_analytical' else '',
                'active': True,
                'validation_status': 'Validated',
                'version': '1.0',
            },
        )
        if code not in {'generic_analytical', 'legacy_availability_response'}:
            Mapping.objects.get_or_create(
                domain='machine_performance',
                intent_type=code,
                scope_type='',
                metric_code='',
                response_template=template,
                defaults={'priority': 100, 'active': True, 'validation_status': 'Validated'},
            )


def remove_seeded_templates(apps, schema_editor):
    Mapping = apps.get_model('reports', 'AIIntentResponseTemplateMapping')
    Template = apps.get_model('reports', 'AIResponseTemplate')
    Mapping.objects.filter(response_template__code__in=TEMPLATES).delete()
    Template.objects.filter(code__in=TEMPLATES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0055_conversation_artifact_refresh_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(db_index=True, default='machine_performance', max_length=80)),
                ('supported_intent_types', models.JSONField(blank=True, default=list)),
                ('supported_scope_types', models.JSONField(blank=True, default=list)),
                ('primary_component', models.CharField(default='generic_result', max_length=120)),
                ('component_order_json', models.JSONField(blank=True, default=list)),
                ('required_data_fields_json', models.JSONField(blank=True, default=list)),
                ('optional_data_fields_json', models.JSONField(blank=True, default=list)),
                ('fallback_template_code', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='To Review', max_length=30)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_response_template',
                'ordering': ['domain', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AIIntentResponseTemplateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, default='machine_performance', max_length=80)),
                ('intent_type', models.CharField(db_index=True, max_length=100)),
                ('scope_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('metric_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='To Review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intent_mappings', to='reports.airesponsetemplate')),
            ],
            options={
                'db_table': 'ai_intent_response_template_mapping',
                'ordering': ['-priority', 'domain', 'intent_type', 'scope_type', 'metric_code'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'intent_type', 'scope_type', 'metric_code', 'response_template'), name='unique_ai_intent_response_template_mapping')],
            },
        ),
        migrations.RunPython(seed_templates, remove_seeded_templates),
    ]
