# Generated by Django 6.0.6 on 2026-08-09 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def configure_prime_movers(apps, schema_editor):
    PowerBIReport = apps.get_model('reports', 'PowerBIReport')
    PowerBIReport.objects.filter(
        report_id='7965812a-e2d7-4950-9651-a148d8fdd235',
    ).update(
        authentication_mode='user_owns_data',
        contains_powerapps_visual=True,
        requires_user_identity=True,
        allow_service_principal_metadata_access=True,
        powerapps_app_name='Prime Movers Operational Status',
        access_instructions=(
            'The Power BI report and its Power Apps application must both be shared '
            'with the connected corporate Microsoft account.'
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0057_backfill_adaptive_template_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='entra_tenant_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='last_entra_authenticated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='access_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='allow_service_principal_metadata_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='authentication_mode',
            field=models.CharField(choices=[('app_owns_data', 'App owns data'), ('user_owns_data', 'User owns data')], default='app_owns_data', max_length=30),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='contains_powerapps_visual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='powerapps_app_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='powerapps_environment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='required_entra_tenant_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='requires_user_identity',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PowerBIAuthenticationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('connect_started', 'Connect started'), ('connect_succeeded', 'Connect succeeded'), ('connect_failed', 'Connect failed'), ('token_refreshed', 'Token refreshed'), ('embed_requested', 'Embed requested'), ('embed_denied', 'Embed denied'), ('disconnected', 'Disconnected')], max_length=40)),
                ('status', models.CharField(default='success', max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authentication_events', to='reports.powerbireport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerbi_authentication_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PowerBIAuthenticationAuditLog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='pbi_auth_user_time_idx'), models.Index(fields=['report', 'created_at'], name='pbi_auth_report_time_idx')],
            },
        ),
        migrations.RunPython(configure_prime_movers, migrations.RunPython.noop),
    ]
