# Generated by Django 6.0.6 on 2026-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0061_bootstrap_downtime_mapping_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimemappingcheckitem',
            name='sanitization_status',
            field=models.CharField(default='unchanged', max_length=30),
        ),
    ]
