# Generated by Django 6.0.6 on 2026-08-12 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0062_downtimemappingcheckitem_sanitization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='auth_source',
            field=models.CharField(choices=[('local', 'Local'), ('microsoft_entra', 'Microsoft Entra'), ('active_directory', 'Active Directory')], db_index=True, default='local', max_length=30),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='directory_distinguished_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='directory_groups_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='directory_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='directory_username',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='last_directory_authenticated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='last_directory_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActiveDirectoryAuthenticationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, max_length=20)),
                ('reason_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ActiveDirectoryAuthenticationAuditLog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveDirectorySyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Partially Completed', 'Partially Completed'), ('Failed', 'Failed')], db_index=True, default='Running', max_length=30)),
                ('discovered_users', models.PositiveIntegerField(default=0)),
                ('created_users', models.PositiveIntegerField(default=0)),
                ('updated_users', models.PositiveIntegerField(default=0)),
                ('disabled_users', models.PositiveIntegerField(default=0)),
                ('skipped_users', models.PositiveIntegerField(default=0)),
                ('failed_users', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.systemintegrationconfig')),
            ],
            options={
                'db_table': 'ActiveDirectorySyncRun',
                'ordering': ['-started_at'],
                'permissions': [('synchronize_active_directory', 'Can synchronize Active Directory')],
            },
        ),
    ]
