# Generated by Django 6.0.6 on 2026-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0063_platformuser_auth_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemintegrationconfig',
            name='integration_type',
            field=models.CharField(choices=[('Power BI', 'Power BI'), ('Power Automate', 'Power Automate'), ('OpenAI', 'OpenAI'), ('Database', 'Database'), ('Data Source', 'Data Source'), ('Storage', 'Storage'), ('Authentication', 'Authentication'), ('Active Directory', 'Active Directory'), ('Notification', 'Notification'), ('Other', 'Other')], max_length=40),
        ),
    ]
