# Generated by Django 6.0.6 on 2026-08-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0064_alter_systemintegrationconfig_integration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='directory_roles_managed',
            field=models.BooleanField(default=True),
        ),
    ]
