# Generated by Django 6.0.6 on 2026-08-12 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0065_platformuser_directory_roles_managed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_added', 'User added'), ('access_changed', 'Access changed'), ('user_enabled', 'User enabled'), ('user_disabled', 'User disabled')], db_index=True, max_length=40)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_access_changes', to=settings.AUTH_USER_MODEL)),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_audit_logs', to='reports.platformuser')),
            ],
            options={
                'db_table': 'UserAccessAuditLog',
                'ordering': ['-created_at'],
                'permissions': [('view_user_access_audit', 'Can view user access audit history')],
            },
        ),
    ]
