# Generated by Django 6.0.6 on 2026-08-14 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


PRIME_REPORTS = {
    '7965812a-e2d7-4950-9651-a148d8fdd235': {
        'code': 'prime-movers-operational-status',
        'visual': '36a5326c9e017bc36902',
    },
    '2fb4cc34-5dab-49d6-8667-0e5e29a6aedd': {
        'code': 'prime-movers-operational-status-v2',
        'visual': '8a2c81ec43d7e077fa4c',
    },
}


def configure_prime_movers(apps, schema_editor):
    Report = apps.get_model('reports', 'PowerBIReport')
    Configuration = apps.get_model('reports', 'PrimeMoversIntegrationConfiguration')
    for report_id, values in PRIME_REPORTS.items():
        report = Report.objects.filter(report_id=report_id).first()
        if not report:
            continue
        report.authentication_mode = 'app_owns_data'
        report.contains_powerapps_visual = True
        report.requires_user_identity = False
        report.launch_mode = 'prime_movers_workspace'
        report.save(update_fields=[
            'authentication_mode', 'contains_powerapps_visual', 'requires_user_identity', 'launch_mode', 'updated_at'
        ])
        Configuration.objects.update_or_create(
            report=report,
            defaults={
                'code': values['code'],
                'powerbi_page_internal_name': '7982fa20087810cade07',
                'powerapps_visual_internal_name': values['visual'],
                'powerapps_visual_type': 'PowerApps_PBI_CV_C29F1DCC_81F5_4973_94AD_0517D44CC06A',
                'powerapps_app_id': 'f344207c-d3a7-45b9-ae09-6cd27f1f18f6',
                'powerapps_tenant_id': '7a1b77be-dbd5-45cb-8e11-b01cbec06667',
                'iframe_enabled': False,
                'new_tab_fallback': True,
                'validation_status': 'To Review',
                'active': True,
            },
        )


def restore_prime_movers(apps, schema_editor):
    Report = apps.get_model('reports', 'PowerBIReport')
    Configuration = apps.get_model('reports', 'PrimeMoversIntegrationConfiguration')
    Configuration.objects.filter(report__report_id__in=PRIME_REPORTS).delete()
    Report.objects.filter(report_id='7965812a-e2d7-4950-9651-a148d8fdd235').update(
        authentication_mode='user_owns_data', contains_powerapps_visual=True,
        requires_user_identity=True, launch_mode='generic_powerbi'
    )
    Report.objects.filter(report_id='2fb4cc34-5dab-49d6-8667-0e5e29a6aedd').update(
        authentication_mode='app_owns_data', contains_powerapps_visual=False,
        requires_user_identity=False, launch_mode='generic_powerbi'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0066_useraccessauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbireport',
            name='launch_mode',
            field=models.CharField(choices=[('generic_powerbi', 'Generic Power BI viewer'), ('prime_movers_workspace', 'Prime Movers workspace')], default='generic_powerbi', max_length=40),
        ),
        migrations.CreateModel(
            name='PrimeMoversIntegrationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('powerbi_page_internal_name', models.CharField(blank=True, max_length=255)),
                ('powerapps_visual_internal_name', models.CharField(blank=True, max_length=255)),
                ('powerapps_visual_type', models.CharField(blank=True, max_length=255)),
                ('powerapps_app_id', models.CharField(blank=True, max_length=128)),
                ('powerapps_tenant_id', models.CharField(blank=True, max_length=128)),
                ('powerapps_environment_id', models.CharField(blank=True, max_length=255)),
                ('powerapps_launch_url', models.URLField(blank=True, max_length=2000)),
                ('iframe_enabled', models.BooleanField(default=False)),
                ('new_tab_fallback', models.BooleanField(default=True)),
                ('context_transfer_mode', models.CharField(default='context_session', max_length=40)),
                ('context_expiration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('To Review', 'To Review'), ('Validated', 'Validated'), ('Invalid', 'Invalid'), ('Disabled', 'Disabled')], default='To Review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prime_movers_configuration', to='reports.powerbireport')),
            ],
            options={
                'db_table': 'PrimeMoversIntegrationConfiguration',
            },
        ),
        migrations.CreateModel(
            name='UserExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('microsoft_entra', 'Microsoft Entra')], default='microsoft_entra', max_length=40)),
                ('tenant_id', models.CharField(max_length=128)),
                ('external_object_id', models.CharField(max_length=128)),
                ('upn', models.EmailField(blank=True, max_length=254)),
                ('windows_identity', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('mapping_status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('conflict', 'Conflict'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserExternalIdentity',
            },
        ),
        migrations.CreateModel(
            name='PowerAppsLaunchContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opaque_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('equipment_id', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('mine_site', models.CharField(blank=True, max_length=255)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('selected_status', models.CharField(blank=True, max_length=255)),
                ('report_context_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'active'), ('consumed', 'consumed'), ('expired', 'expired'), ('revoked', 'revoked')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerapps_launch_contexts', to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_contexts', to='reports.primemoversintegrationconfiguration')),
                ('external_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_contexts', to='reports.userexternalidentity')),
            ],
            options={
                'db_table': 'PowerAppsLaunchContext',
            },
        ),
        migrations.CreateModel(
            name='PrimeMoversIntegrationExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_identity', models.CharField(blank=True, max_length=255)),
                ('entra_object_id', models.CharField(blank=True, max_length=128)),
                ('selected_strategy', models.CharField(default='dual_workspace', max_length=40)),
                ('powerbi_status', models.CharField(blank=True, max_length=40)),
                ('powerapps_status', models.CharField(blank=True, max_length=40)),
                ('selected_machine', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('load_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.powerappslaunchcontext')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.powerbireport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PrimeMoversIntegrationExecutionLog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', 'created_at'], name='pm_exec_report_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userexternalidentity',
            index=models.Index(fields=['user', 'provider', 'active'], name='ext_identity_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='userexternalidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'tenant_id', 'external_object_id'), name='unique_external_identity_object'),
        ),
        migrations.AddIndex(
            model_name='powerappslaunchcontext',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='pa_context_user_idx'),
        ),
        migrations.RunPython(configure_prime_movers, restore_prime_movers),
    ]
