# Generated by Django 6.0.6 on 2026-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0077_remove_prime_movers_special_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbireport',
            name='background_type',
            field=models.CharField(choices=[('default', 'Default'), ('transparent', 'Transparent')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='bookmarks_pane_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='default_page_internal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='default_rls_role',
            field=models.CharField(blank=True, default='Global', max_length=128),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='display_option',
            field=models.CharField(choices=[('fit_to_page', 'Fit to page'), ('fit_to_width', 'Fit to width'), ('actual_size', 'Actual size')], default='fit_to_page', max_length=30),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='filter_pane_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='opening_profile_name',
            field=models.CharField(blank=True, default='Standard Power BI', max_length=120),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='page_navigation_visible',
            field=models.BooleanField(default=True),
        ),
    ]
