# Generated by Django 6.0.6 on 2026-08-22 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0078_powerbi_report_opening_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbireport',
            name='configuration_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('needs_review', 'Needs Review'), ('complete', 'Complete'), ('invalid', 'Invalid')], default='needs_review', max_length=30),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='configuration_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='last_test_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='last_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='open_behavior',
            field=models.CharField(choices=[('inside_mining360', 'Inside Mining 360'), ('new_mining360_page', 'New Mining 360 page'), ('fullscreen', 'Full screen'), ('external_powerbi', 'External Power BI')], default='inside_mining360', max_length=40),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_powerbi_report_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='supports_chatbot_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='supports_embedded_filtering',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='troubleshooting_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='troubleshooting_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='troubleshooting_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_powerbi_report_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReportConfigurationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('before_json', models.JSONField(default=dict)),
                ('after_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_audit_logs', to='reports.powerbireport')),
            ],
            options={
                'db_table': 'report_configuration_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfigurationTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], max_length=20)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_test_runs', to='reports.powerbireport')),
            ],
            options={
                'db_table': 'report_configuration_test_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportConfigurationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('published', models.BooleanField(default=False)),
                ('restored_from_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_versions', to='reports.powerbireport')),
            ],
            options={
                'db_table': 'report_configuration_versions',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('report', 'version'), name='unique_report_configuration_version')],
            },
        ),
        migrations.CreateModel(
            name='ReportContextParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120)),
                ('display_name', models.CharField(max_length=180)),
                ('source', models.CharField(choices=[('chatbot', 'Chatbot context'), ('homepage', 'Homepage context'), ('reporting_hub', 'Reporting Hub context'), ('query_string', 'Query string'), ('user_profile', 'User profile'), ('fixed_default', 'Fixed default'), ('powerbi_filter', 'Power BI filter'), ('powerapps_context', 'Power Apps launch context')], max_length=40)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('powerbi_table', models.CharField(blank=True, max_length=255)),
                ('powerbi_column', models.CharField(blank=True, max_length=255)),
                ('operator', models.CharField(choices=[('In', 'In'), ('Equals', 'Equals'), ('Contains', 'Contains')], default='In', max_length=20)),
                ('supports_multiple_values', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_parameters', to='reports.powerbireport')),
            ],
            options={
                'db_table': 'report_context_parameters',
                'ordering': ['display_order', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('report', 'code'), name='unique_report_context_parameter')],
            },
        ),
    ]
