# Generated by Django 6.0.6 on 2026-08-23 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0079_powerbireport_configuration_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_code', models.CharField(blank=True, max_length=64)),
                ('illustration_code', models.CharField(blank=True, max_length=64)),
                ('accent_code', models.CharField(choices=[('yellow', 'Mining 360 Yellow'), ('emerald', 'Emerald'), ('blue', 'Blue'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('amber', 'Amber'), ('rose', 'Rose'), ('slate', 'Slate')], default='slate', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('Imported', 'Imported'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Deprecated', 'Deprecated')], default='To Review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_categories',
                'ordering': ['display_order', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='accent_code',
            field=models.CharField(blank=True, choices=[('yellow', 'Mining 360 Yellow'), ('emerald', 'Emerald'), ('blue', 'Blue'), ('purple', 'Purple'), ('cyan', 'Cyan'), ('amber', 'Amber'), ('rose', 'Rose'), ('slate', 'Slate')], max_length=20),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='business_purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='card_badge',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='card_style',
            field=models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='icon_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='illustration_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='powerbi_screenshot_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='secondary_categories_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='short_description',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='technical_owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='report_visuals/thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='thumbnail_focal_x',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='thumbnail_focal_y',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='thumbnail_source',
            field=models.CharField(choices=[('automatic', 'Automatic fallback'), ('manual_thumbnail', 'Manual thumbnail'), ('powerbi_screenshot', 'Power BI screenshot'), ('report_illustration', 'Report illustration'), ('category_illustration', 'Category illustration')], default='automatic', max_length=32),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='thumbnail_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportingreportpreference',
            name='visual_identity_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('default', 'Default'), ('needs_review', 'Needs Review'), ('invalid', 'Invalid')], default='needs_review', max_length=24),
        ),
        migrations.AlterField(
            model_name='reportingreportpreference',
            name='category',
            field=models.CharField(choices=[('fleet_performance', 'Fleet Performance'), ('maintenance_reliability', 'Maintenance & Reliability'), ('operations', 'Operations'), ('fuel_connectivity', 'Fuel & Connectivity'), ('parts_aftermarket', 'Parts & Aftermarket'), ('management_reports', 'Management Reports'), ('lifecycle_cost', 'Lifecycle Cost'), ('customer_performance', 'Customer Performance'), ('other', 'Other')], default='other', max_length=64),
        ),
        migrations.CreateModel(
            name='ReportVisualAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('asset_type', models.CharField(choices=[('report_thumbnail', 'Report thumbnail'), ('report_illustration', 'Report illustration'), ('category_illustration', 'Category illustration'), ('category_icon', 'Category icon')], max_length=32)),
                ('file', models.FileField(upload_to='report_visuals/assets/%Y/%m/')),
                ('illustration_code', models.CharField(blank=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('Imported', 'Imported'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Deprecated', 'Deprecated')], default='To Review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_assets', to='reports.reportcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_visual_assets',
                'ordering': ['name'],
            },
        ),
    ]
