# Generated by Django 6.0.6 on 2026-08-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0081_seed_report_visual_identities'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingreportpreference',
            name='selected_visual_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_preferences', to='reports.reportvisualasset'),
        ),
    ]
