# Generated by Django 6.0.6 on 2026-08-23 11:57

from django.db import migrations, models


def seed_viewer_periods(apps, schema_editor):
    Report = apps.get_model("reports", "PowerBIReport")
    Report.objects.filter(viewer_available_periods=[]).update(
        viewer_available_periods=["ytd", "last_12_months", "custom"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0084_refine_report_card_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_allow_open_powerbi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_auto_apply_presets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_available_periods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_custom_range_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_date_column',
            field=models.CharField(blank=True, default='Date', max_length=255),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_date_table',
            field=models.CharField(blank=True, default='Date', max_length=255),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_default_period',
            field=models.CharField(choices=[('ytd', 'Year to Date'), ('mtd', 'Month to Date'), ('last_month', 'Last Month'), ('last_30_days', 'Last 30 Days'), ('last_12_months', 'Last 12 Months'), ('custom', 'Custom')], default='ytd', max_length=30),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_external_page_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_focus_mode_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_fullscreen_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_reset_behavior',
            field=models.CharField(choices=[('defaults', 'Restore configured defaults'), ('clear', 'Clear Mining 360 filters')], default='defaults', max_length=20),
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='viewer_show_filter_bar',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(seed_viewer_periods, migrations.RunPython.noop),
    ]
