# Generated by Django 6.0.6 on 2026-09-01 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0101_configure_complete_fleet_performance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnswerabilityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=120, unique=True)),
                ('minimum_entity_confidence', models.PositiveSmallIntegerField(default=90)),
                ('minimum_knowledge_confidence', models.PositiveSmallIntegerField(default=90)),
                ('require_structured_evidence', models.BooleanField(default=True)),
                ('require_document_evidence', models.BooleanField(default=True)),
                ('allow_general_model_knowledge', models.BooleanField(default=False)),
                ('allow_hypothesis_mode', models.BooleanField(default=False)),
                ('show_available_alternatives', models.BooleanField(default=True)),
                ('show_source_summary', models.BooleanField(default=True)),
                ('log_data_gaps', models.BooleanField(default=True)),
                ('allow_data_gap_reporting', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AIAnswerabilityConfiguration',
            },
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='detailed_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='detailed_description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='display_name_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='display_name_fr',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='display_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='domain_code',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='example_questions_en_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='example_questions_fr_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='readiness_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='readiness_status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Limited', 'Limited'), ('Needs Configuration', 'Needs Configuration'), ('Disabled', 'Disabled'), ('Invalid', 'Invalid')], db_index=True, default='Needs Configuration', max_length=30),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='required_configuration_checks_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='required_data_sources_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='required_permissions_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='short_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='short_description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supported_entities_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supported_intents_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supported_metrics_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supported_operations_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supports_comparison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supports_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supports_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supports_navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supports_ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiagentcapability',
            name='supports_trend',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AIAnswerabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('reason_code', models.CharField(blank=True, max_length=120)),
                ('capability_code', models.CharField(blank=True, max_length=120)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AIAnswerabilityEvent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_field_code', models.SlugField(max_length=120)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('display_name_en', models.CharField(max_length=180)),
                ('display_name_fr', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('synonyms_json', models.JSONField(blank=True, default=list)),
                ('data_type', models.CharField(default='Text', max_length=80)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('source_type', models.CharField(choices=[('semantic_column', 'Semantic Column'), ('semantic_measure', 'Semantic Measure'), ('knowledge', 'Knowledge Base'), ('business_rule', 'Business Rule'), ('none', 'Not Configured')], default='none', max_length=40)),
                ('semantic_model_id', models.CharField(blank=True, max_length=128)),
                ('table_name', models.CharField(blank=True, max_length=255)),
                ('column_name', models.CharField(blank=True, max_length=255)),
                ('measure_name', models.CharField(blank=True, max_length=255)),
                ('knowledge_section', models.CharField(blank=True, max_length=255)),
                ('permission_code', models.CharField(blank=True, max_length=150)),
                ('nullable', models.BooleanField(default=True)),
                ('configuration_status', models.CharField(choices=[('Configured', 'Configured'), ('Not Configured', 'Not Configured'), ('Invalid', 'Invalid'), ('Disabled', 'Disabled')], db_index=True, default='Not Configured', max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='To Review', max_length=20)),
                ('source_priority', models.PositiveIntegerField(default=100)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'BusinessDataField',
                'ordering': ['entity_type', 'source_priority', 'display_name_en'],
                'constraints': [models.UniqueConstraint(fields=('canonical_field_code', 'entity_type'), name='unique_business_data_field')],
            },
        ),
        migrations.CreateModel(
            name='SourcePrecedenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('primary_source', models.CharField(max_length=255)),
                ('secondary_source', models.CharField(blank=True, max_length=255)),
                ('conditions_json', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('validation_status', models.CharField(choices=[('Draft', 'Draft'), ('To Review', 'To Review'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='To Review', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedence_rules', to='reports.businessdatafield')),
            ],
            options={
                'db_table': 'SourcePrecedenceRule',
                'ordering': ['business_field', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='UnansweredInformationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_question', models.TextField()),
                ('normalized_question', models.TextField(blank=True)),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_identifier', models.CharField(blank=True, max_length=255)),
                ('requested_field_code', models.CharField(db_index=True, max_length=120)),
                ('answerability_status', models.CharField(max_length=80)),
                ('reason_code', models.CharField(blank=True, max_length=120)),
                ('requested_source_type', models.CharField(blank=True, max_length=100)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_requested_at', models.DateTimeField(auto_now_add=True)),
                ('last_requested_at', models.DateTimeField(auto_now=True)),
                ('sample_questions_json', models.JSONField(blank=True, default=list)),
                ('suggested_data_source', models.CharField(blank=True, max_length=255)),
                ('business_priority', models.CharField(default='Normal', max_length=40)),
                ('assigned_owner', models.CharField(blank=True, max_length=180)),
                ('resolution_status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Source Identified', 'Source Identified'), ('Mapping In Progress', 'Mapping In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Out of Scope', 'Out of Scope')], db_index=True, default='New', max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_by_user', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_gaps', to='reports.aiconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unanswered_information_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UnansweredInformationRequirement',
                'ordering': ['-last_requested_at'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'entity_type', 'requested_field_code'), name='unique_unanswered_requirement')],
            },
        ),
    ]
