# Generated by Django 6.0.6 on 2026-09-03 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0107_seed_chat_production_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_execution_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ROUTING', 'Routing'), ('RESOLVING_CONTEXT', 'Resolving Context'), ('CHECKING_ANSWERABILITY', 'Checking Answerability'), ('EXECUTING_DATA_SOURCE', 'Executing Data Source'), ('RETRIEVING_KNOWLEDGE', 'Retrieving Knowledge'), ('GENERATING_RESPONSE', 'Generating Response'), ('VALIDATING_GROUNDING', 'Validating Grounding'), ('RENDERING', 'Rendering'), ('SUCCEEDED', 'Succeeded'), ('NEEDS_CLARIFICATION', 'Needs Clarification'), ('ABSTAINED', 'Abstained'), ('RETRYABLE_FAILED', 'Retryable Failed'), ('PERMANENT_FAILED', 'Permanent Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=40)),
                ('suggestion_code', models.CharField(blank=True, max_length=140)),
                ('action_code', models.CharField(blank=True, max_length=120)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('failure_category', models.CharField(blank=True, max_length=80)),
                ('status_history_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_executions', to='reports.aiconversationmessage')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.aiconversation')),
                ('retried_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_executions', to='reports.aiconversationexecution')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.aiconversationmessage')),
            ],
            options={
                'db_table': 'AIConversationExecution',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['conversation', 'status', '-started_at'], name='ai_exec_conv_status')],
            },
        ),
    ]
