# Generated by Django 6.0.6 on 2026-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0109_business_mapping_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsynchronizationrun',
            name='source_context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
