# Generated by Django 6.0.6 on 2026-09-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0110_business_mapping_source_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFleetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=255)),
                ('source_table', models.CharField(default='EquipmentList_MiningProd', max_length=120)),
                ('semantic_model_id', models.CharField(max_length=120)),
                ('equipment_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('site', models.CharField(blank=True, db_index=True, max_length=500)),
                ('normalized_site', models.CharField(blank=True, db_index=True, max_length=500)),
                ('equipment', models.CharField(blank=True, db_index=True, max_length=255)),
                ('model', models.CharField(blank=True, db_index=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('equipment_family', models.CharField(blank=True, db_index=True, max_length=255)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source_status', models.CharField(blank=True, max_length=120)),
                ('smu', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_last_seen_at', models.DateTimeField(db_index=True)),
                ('synchronization_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_analysis_records', to='reports.mappingsynchronizationrun')),
            ],
            options={
                'db_table': 'bm_equipment_fleet_analysis',
                'ordering': ['site', 'model', 'equipment', 'serial_number'],
                'indexes': [models.Index(fields=['active', 'normalized_site', 'model'], name='bm_equip_analysis_site_model'), models.Index(fields=['active', 'equipment_family'], name='bm_equip_analysis_family')],
                'constraints': [models.UniqueConstraint(fields=('synchronization_run', 'source_record_id'), name='bm_unique_equipment_analysis_run')],
            },
        ),
    ]
