# Generated by Django 6.0.6 on 2026-09-05 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def freeze_publication_source_records(apps, schema_editor):
    MappingPublication = apps.get_model("reports", "MappingPublication")
    SourceAccountRecord = apps.get_model("reports", "SourceAccountRecord")
    for publication in MappingPublication.objects.all().iterator():
        snapshot = publication.snapshot_json or {}
        mappings = snapshot.get("mappings", [])
        changed = False
        for row in mappings:
            if "source_account_codes" in row:
                continue
            records = list(SourceAccountRecord.objects.filter(
                canonical_account_id=row.get("account_id"), active=True,
            ).values("source_system", "source_record_id", "code_cic", "company_code", "branch_code", "country"))
            row["source_records"] = records
            row["source_account_codes"] = sorted({record["source_record_id"] for record in records})
            changed = True
        if changed:
            snapshot["mappings"] = mappings
            publication.snapshot_json = snapshot
            publication.save(update_fields=["snapshot_json"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0111_equipment_fleet_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsynchronizationrun',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mappingsynchronizationrun',
            name='records_rejected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mappingsynchronizationrun',
            name='records_unchanged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BusinessOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity_code', models.CharField(db_index=True, max_length=120)),
                ('revenue_lens', models.CharField(db_index=True, default='ALL', max_length=20)),
                ('classification', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Acknowledged', 'Acknowledged'), ('Actioned', 'Actioned'), ('Dismissed', 'Dismissed'), ('Resolved', 'Resolved')], db_index=True, default='Open', max_length=20)),
                ('metric_values_json', models.JSONField(default=dict)),
                ('threshold_values_json', models.JSONField(default=dict)),
                ('gap_values_json', models.JSONField(blank=True, default=dict)),
                ('evidence_json', models.JSONField(default=list)),
                ('rule_version', models.CharField(max_length=80)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_opportunities', to='reports.businessaccount')),
                ('minesite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_opportunities', to='reports.minesite')),
            ],
            options={
                'db_table': 'br_opportunity',
                'ordering': ['severity', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessReviewSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_rule_version', models.CharField(db_index=True, default='1.0', max_length=80)),
                ('status', models.CharField(choices=[('Generating', 'Generating'), ('Ready', 'Ready'), ('Limited', 'Limited'), ('Failed', 'Failed'), ('Superseded', 'Superseded')], db_index=True, default='Generating', max_length=20)),
                ('confidence_status', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Not Ready', 'Not Ready')], db_index=True, default='Not Ready', max_length=20)),
                ('context_json', models.JSONField(default=dict)),
                ('metrics_json', models.JSONField(default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_business_review_snapshots', to=settings.AUTH_USER_MODEL)),
                ('mapping_publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_review_snapshots', to='reports.mappingpublication')),
                ('source_synchronization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_review_snapshots', to='reports.mappingsynchronizationrun')),
            ],
            options={
                'db_table': 'br_snapshot',
                'ordering': ['-generated_at'],
                'permissions': [('view_business_review', 'Can view Business Review'), ('view_business_review_financials', 'Can view Business Review financials'), ('view_business_review_fleet', 'Can view Business Review fleet'), ('compare_business_entities', 'Can compare Business Review entities'), ('export_business_review', 'Can export Business Review'), ('create_business_review_action', 'Can create Business Review actions'), ('assign_business_review_action', 'Can assign Business Review actions'), ('complete_business_review_action', 'Can complete Business Review actions'), ('create_business_decision', 'Can create Business Review decisions'), ('view_business_review_data_confidence', 'Can view Business Review data confidence'), ('preview_business_review_draft', 'Can preview Business Review with unpublished mappings')],
            },
        ),
        migrations.CreateModel(
            name='BusinessReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(blank=True, max_length=120)),
                ('business_lens', models.CharField(default='ALL', max_length=20)),
                ('evidence_snapshot_json', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Medium', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Open', max_length=20)),
                ('expected_impact', models.TextField(blank=True)),
                ('decision', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_review_actions', to='reports.businessaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_review_actions', to=settings.AUTH_USER_MODEL)),
                ('minesite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_review_actions', to='reports.minesite')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_actions', to='reports.businessopportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business_review_actions', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_actions', to='reports.businessreviewsnapshot')),
            ],
            options={
                'db_table': 'br_action',
                'ordering': ['status', 'priority', 'due_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='reports.businessreviewsnapshot'),
        ),
        migrations.CreateModel(
            name='BusinessDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('evidence_json', models.JSONField(default=list)),
                ('decision_date', models.DateField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expected_result', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_decisions', to='reports.businessaccount')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_decisions', to=settings.AUTH_USER_MODEL)),
                ('minesite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_decisions', to='reports.minesite')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='reports.businessreviewaction')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='reports.businessreviewsnapshot')),
            ],
            options={
                'db_table': 'br_decision',
                'ordering': ['-decision_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_code', models.CharField(db_index=True, max_length=120)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Acknowledged', 'Acknowledged'), ('Actioned', 'Actioned'), ('Dismissed', 'Dismissed'), ('Resolved', 'Resolved')], db_index=True, default='Open', max_length=20)),
                ('business_impact_json', models.JSONField(default=dict)),
                ('evidence_json', models.JSONField(default=list)),
                ('rule_version', models.CharField(max_length=80)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_risks', to='reports.businessaccount')),
                ('minesite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_risks', to='reports.minesite')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='reports.businessreviewsnapshot')),
            ],
            options={
                'db_table': 'br_risk',
                'ordering': ['severity', '-detected_at'],
            },
        ),
        migrations.AddField(
            model_name='businessreviewaction',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_actions', to='reports.businessrisk'),
        ),
        migrations.CreateModel(
            name='BusinessPortfolioThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('entity_type', models.CharField(default='MineSite', max_length=30)),
                ('revenue_lens', models.CharField(choices=[('ALL', 'All Mining'), ('PRIME', 'Machine'), ('PARTS', 'Parts'), ('SERVICE', 'Service'), ('RENTAL', 'Rental')], db_index=True, default='ALL', max_length=20)),
                ('scope_country', models.CharField(blank=True, db_index=True, max_length=120)),
                ('method', models.CharField(choices=[('Median', 'Median'), ('Percentile', 'Percentile'), ('Business Target', 'Business Target'), ('Fixed Governed Threshold', 'Fixed Governed Threshold'), ('Peer Group', 'Peer Group')], default='Median', max_length=40)),
                ('revenue_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fleet_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rule_version', models.CharField(default='1.0', max_length=80)),
                ('validation_status', models.CharField(db_index=True, default='To Review', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business_portfolio_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'br_portfolio_threshold_rule',
                'ordering': ['revenue_lens', 'scope_country', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='br_threshold_dates_valid')],
            },
        ),
        migrations.CreateModel(
            name='BusinessReviewSavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('filters_json', models.JSONField(default=dict)),
                ('sorting_json', models.JSONField(blank=True, default=list)),
                ('visualization', models.CharField(default='executive_overview', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_review_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'br_saved_view',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='br_unique_user_saved_view')],
            },
        ),
        migrations.AddConstraint(
            model_name='businessreviewsnapshot',
            constraint=models.UniqueConstraint(fields=('mapping_publication', 'source_synchronization', 'business_rule_version'), name='br_unique_snapshot_contract'),
        ),
        migrations.AddConstraint(
            model_name='businessopportunity',
            constraint=models.UniqueConstraint(fields=('snapshot', 'opportunity_code', 'business_account', 'minesite', 'revenue_lens'), name='br_unique_opportunity_scope'),
        ),
        migrations.AddConstraint(
            model_name='businessrisk',
            constraint=models.UniqueConstraint(fields=('snapshot', 'risk_code', 'business_account', 'minesite'), name='br_unique_risk_scope'),
        ),
        migrations.RunPython(freeze_publication_source_records, migrations.RunPython.noop),
    ]
