# Generated by Django 6.0.6 on 2026-09-05 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0113_source_account_field_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_account_code', models.CharField(max_length=160, unique=True)),
                ('key_account_name', models.CharField(db_index=True, max_length=500)),
                ('normalized_key_account_name', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_key_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_key_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bm_key_account',
                'ordering': ['key_account_name'],
            },
        ),
        migrations.CreateModel(
            name='KeyAccountMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='key_account_memberships', to='reports.businessaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_key_account_memberships', to=settings.AUTH_USER_MODEL)),
                ('key_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='reports.keyaccount')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_key_account_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bm_key_account_membership',
                'ordering': ['key_account', 'business_account__canonical_account_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='keyaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('normalized_key_account_name',), name='bm_unique_active_key_account_name'),
        ),
        migrations.AddIndex(
            model_name='keyaccountmembership',
            index=models.Index(fields=['key_account', 'active'], name='bm_key_account_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyaccountmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('business_account',), name='bm_unique_active_key_account_membership'),
        ),
    ]
