# Generated by Django 6.0.6 on 2026-09-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0114_keyaccount_keyaccountmembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountminesitemapping',
            name='account_role',
            field=models.CharField(choices=[('Mapped Account', 'Mapped Account'), ('Mine Owner', 'Mine Owner'), ('Mine Operator', 'Mine Operator'), ('Mining Contractor', 'Mining Contractor'), ('Billing Account', 'Billing Account'), ('Procurement Account', 'Procurement Account'), ('Parts Account', 'Parts Account'), ('Service Account', 'Service Account'), ('Equipment Account', 'Equipment Account'), ('Parent Group', 'Parent Group'), ('Holding Company', 'Holding Company'), ('Partner', 'Partner'), ('Prospect', 'Prospect'), ('Other', 'Other'), ('Head Office', 'Head Office'), ('Regional Office', 'Regional Office'), ('Internal Account', 'Internal Account'), ('Distributor', 'Distributor'), ('Supplier', 'Supplier'), ('Non-Mining Customer', 'Non-Mining Customer'), ('Government', 'Government'), ('No MineSite Required', 'No MineSite Required'), ('Unknown', 'Unknown'), ('To Review', 'To Review')], max_length=60),
        ),
    ]
