# Generated by Django 6.0.6 on 2026-09-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0115_alter_accountminesitemapping_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingsynchronizationrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mappingsynchronizationrun',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mappingsynchronizationrun',
            name='stage_code',
            field=models.CharField(blank=True, default='queued', max_length=60),
        ),
        migrations.AddField(
            model_name='mappingsynchronizationrun',
            name='stage_label',
            field=models.CharField(blank=True, default='Waiting for the synchronization worker', max_length=255),
        ),
    ]
