# Generated by Django 6.0.6 on 2026-09-06 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def forward_country_hierarchy(apps, schema_editor):
    CountryAccount = apps.get_model('reports', 'CountryAccount')
    CountryMembership = apps.get_model('reports', 'CountryAccountMembership')
    KeyCountryMembership = apps.get_model('reports', 'KeyAccountCountryMembership')
    LegacyMembership = apps.get_model('reports', 'KeyAccountMembership')
    grouped = {}
    for membership in LegacyMembership.objects.filter(active=True).select_related('key_account', 'business_account'):
        country = (membership.business_account.country or 'UNSPECIFIED').upper()
        group_key = (membership.key_account_id, country)
        country_account = grouped.get(group_key)
        if not country_account:
            name = f"{membership.key_account.key_account_name} - {country}"
            country_account = CountryAccount.objects.create(
                country_account_code=f"MIGRATED-{membership.key_account_id}-{country}",
                country_account_name=name,
                normalized_country_account_name=' '.join(name.casefold().split()),
                country=country,
                created_by_id=membership.created_by_id,
                updated_by_id=membership.created_by_id,
            )
            KeyCountryMembership.objects.create(
                key_account_id=membership.key_account_id,
                country_account=country_account,
                created_by_id=membership.created_by_id,
            )
            grouped[group_key] = country_account
        CountryMembership.objects.create(
            country_account=country_account,
            business_account_id=membership.business_account_id,
            created_by_id=membership.created_by_id,
        )
        membership.active = False
        membership.save(update_fields=['active'])


def reverse_country_hierarchy(apps, schema_editor):
    CountryMembership = apps.get_model('reports', 'CountryAccountMembership')
    KeyCountryMembership = apps.get_model('reports', 'KeyAccountCountryMembership')
    LegacyMembership = apps.get_model('reports', 'KeyAccountMembership')
    for key_membership in KeyCountryMembership.objects.filter(active=True):
        for membership in CountryMembership.objects.filter(country_account_id=key_membership.country_account_id, active=True):
            legacy, _ = LegacyMembership.objects.get_or_create(
                key_account_id=key_membership.key_account_id,
                business_account_id=membership.business_account_id,
                defaults={'created_by_id': membership.created_by_id},
            )
            legacy.active = True
            legacy.save(update_fields=['active'])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0116_business_mapping_sync_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_account_code', models.CharField(max_length=160, unique=True)),
                ('country_account_name', models.CharField(db_index=True, max_length=500)),
                ('normalized_country_account_name', models.CharField(db_index=True, max_length=500)),
                ('country', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_country_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_country_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bm_country_account',
                'ordering': ['country', 'country_account_name'],
            },
        ),
        migrations.CreateModel(
            name='CountryAccountMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_account_memberships', to='reports.businessaccount')),
                ('country_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='reports.countryaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_country_account_memberships', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_country_account_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bm_country_account_membership',
                'ordering': ['country_account', 'business_account__canonical_account_name'],
            },
        ),
        migrations.CreateModel(
            name='KeyAccountCountryMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('country_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='key_memberships', to='reports.countryaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_key_account_country_memberships', to=settings.AUTH_USER_MODEL)),
                ('key_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_memberships', to='reports.keyaccount')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_key_account_country_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bm_key_account_country_membership',
                'ordering': ['key_account', 'country_account__country', 'country_account__country_account_name'],
            },
        ),
        migrations.RunPython(forward_country_hierarchy, reverse_country_hierarchy),
        migrations.AddConstraint(
            model_name='countryaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('country', 'normalized_country_account_name'), name='bm_unique_active_country_account_name'),
        ),
        migrations.AddIndex(
            model_name='countryaccountmembership',
            index=models.Index(fields=['country_account', 'active'], name='bm_country_account_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='countryaccountmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('business_account',), name='bm_unique_active_country_account_membership'),
        ),
        migrations.AddIndex(
            model_name='keyaccountcountrymembership',
            index=models.Index(fields=['key_account', 'active'], name='bm_key_country_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyaccountcountrymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('country_account',), name='bm_unique_active_key_country_membership'),
        ),
    ]
