# Generated by Django 6.0.6 on 2026-09-06 11:14

from django.db import migrations, models


COMPANY_COUNTRY = {
    '22': 'FR', '27': 'FR', '31': 'BF', '32': 'CI', '33': 'BJ',
    '34': 'GN', '36': 'ML', '37': 'MR', '38': 'MR', '39': 'NE',
    '40': 'SN', '41': 'TG', '42': 'FR', '61': 'BF', '62': 'BF',
}


def backfill_operating_country(apps, schema_editor):
    BusinessAccount = apps.get_model('reports', 'BusinessAccount')
    SourceAccountRecord = apps.get_model('reports', 'SourceAccountRecord')
    Revenue = apps.get_model('reports', 'RevenueSourceSnapshot')
    CountryAccount = apps.get_model('reports', 'CountryAccount')
    CountryMembership = apps.get_model('reports', 'CountryAccountMembership')
    KeyCountryMembership = apps.get_model('reports', 'KeyAccountCountryMembership')

    revenue_by_source = {}
    revenue_country_totals = {}
    for row in Revenue.objects.filter(active=True).only('id', 'source_account_code', 'company_code', 'revenue_ytd_eur'):
        country = COMPANY_COUNTRY.get((row.company_code or '').strip().upper(), '')
        if row.operating_country != country:
            row.operating_country = country
            row.save(update_fields=['operating_country'])
        if country:
            revenue_by_source.setdefault(row.source_account_code, set()).add(country)
            key = (row.source_account_code, country)
            revenue_country_totals[key] = revenue_country_totals.get(key, 0) + (row.revenue_ytd_eur or 0)

    operating_by_account = {}
    for record in SourceAccountRecord.objects.filter(active=True):
        countries = sorted(revenue_by_source.get(record.source_record_id, set()))
        record.origin_country = record.country
        record.operating_countries_json = countries
        record.save(update_fields=['origin_country', 'operating_countries_json'])
        if record.canonical_account_id:
            operating_by_account.setdefault(record.canonical_account_id, set()).update(countries)

    for account in BusinessAccount.objects.all():
        account.origin_country = account.country
        account.operating_countries_json = sorted(operating_by_account.get(account.id, set()))
        account.save(update_fields=['origin_country', 'operating_countries_json'])

    # 0117 generated Country Accounts from customer origin. Rebuild only those
    # generated records; manually governed Country Accounts are preserved.
    generated = list(CountryAccount.objects.filter(active=True, country_account_code__startswith='MIGRATED-'))
    CountryAccount.objects.filter(id__in=[item.id for item in generated]).update(active=False)
    for old_country_account in generated:
        key_link = KeyCountryMembership.objects.filter(country_account=old_country_account, active=True).first()
        memberships = list(CountryMembership.objects.filter(country_account=old_country_account, active=True))
        # Release the active name/country uniqueness before rebuilding the
        # generated group under the operating-country hierarchy.
        for membership in memberships:
            account_id = membership.business_account_id
            countries = operating_by_account.get(account_id, set())
            source_codes = list(SourceAccountRecord.objects.filter(active=True, canonical_account_id=account_id).values_list('source_record_id', flat=True))
            ranked = sorted(
                countries,
                key=lambda country: -sum(revenue_country_totals.get((code, country), 0) for code in source_codes),
            )
            membership.active = False
            membership.save(update_fields=['active'])
            if not ranked or not key_link:
                continue
            country = ranked[0]
            code = f'MIGRATED-OPER-{key_link.key_account_id}-{country}'
            name = f'{key_link.key_account.key_account_name} - {country}'
            target, _ = CountryAccount.objects.get_or_create(
                country_account_code=code,
                defaults={
                    'country_account_name': name,
                    'normalized_country_account_name': ' '.join(name.casefold().split()),
                    'country': country,
                    'created_by_id': membership.created_by_id,
                    'updated_by_id': membership.created_by_id,
                },
            )
            KeyCountryMembership.objects.get_or_create(
                key_account_id=key_link.key_account_id,
                country_account=target,
                defaults={'created_by_id': membership.created_by_id},
            )
            CountryMembership.objects.get_or_create(
                country_account=target,
                business_account_id=account_id,
                defaults={'created_by_id': membership.created_by_id},
            )
        KeyCountryMembership.objects.filter(country_account=old_country_account, active=True).update(active=False)


def reverse_backfill(apps, schema_editor):
    # Source country remains untouched, so only the derived fields are cleared.
    apps.get_model('reports', 'RevenueSourceSnapshot').objects.update(operating_country='')
    apps.get_model('reports', 'SourceAccountRecord').objects.update(origin_country='', operating_countries_json=[])
    apps.get_model('reports', 'BusinessAccount').objects.update(origin_country='', operating_countries_json=[])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0117_country_account_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='operating_countries_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='origin_country',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='revenuesourcesnapshot',
            name='operating_country',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sourceaccountrecord',
            name='operating_countries_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sourceaccountrecord',
            name='origin_country',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.RunPython(backfill_operating_country, reverse_backfill),
    ]
