# Generated by Django 6.0.6 on 2026-09-07 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0122_business_account_operating_country_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationAccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=255)),
                ('company_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('branch_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('customer_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=160)),
                ('entry_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('accounting_date', models.DateField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('consolidated_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'rec_accounting_entry',
                'ordering': ['company_code', 'document_number', 'accounting_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDeliveryInvoiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=255)),
                ('company_code', models.CharField(db_index=True, max_length=40)),
                ('order_branch_code', models.CharField(db_index=True, max_length=40)),
                ('order_number', models.CharField(db_index=True, max_length=120)),
                ('line_number', models.CharField(db_index=True, max_length=80)),
                ('customer_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('delivery_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('cancellation_invoice_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('invoice_branch_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('invoice_service_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=160)),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('invoiced_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('delivered_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('line_status', models.CharField(blank=True, db_index=True, max_length=80)),
                ('operation_nature', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'rec_delivery_invoice_link',
                'ordering': ['company_code', 'order_branch_code', 'order_number', 'line_number', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationInvoiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=255)),
                ('company_code', models.CharField(db_index=True, max_length=40)),
                ('branch_code', models.CharField(db_index=True, max_length=40)),
                ('service_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('invoice_number', models.CharField(db_index=True, max_length=120)),
                ('master_invoice_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('customer_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('invoice_date', models.DateField(blank=True, db_index=True, null=True)),
                ('transaction_origin', models.CharField(blank=True, max_length=20)),
                ('invoice_status', models.CharField(blank=True, db_index=True, max_length=80)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'rec_invoice_header',
                'ordering': ['company_code', 'branch_code', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=255)),
                ('company_code', models.CharField(db_index=True, max_length=40)),
                ('branch_code', models.CharField(db_index=True, max_length=40)),
                ('order_number', models.CharField(db_index=True, max_length=120)),
                ('line_number', models.CharField(db_index=True, max_length=80)),
                ('customer_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=160)),
                ('order_date', models.DateField(blank=True, db_index=True, null=True)),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('current_invoiced_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('current_delivered_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True)),
                ('currency', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'rec_order_line',
                'ordering': ['company_code', 'branch_code', 'order_number', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MATCHED', 'MATCHED'), ('PARTIALLY_INVOICED', 'PARTIALLY_INVOICED'), ('CANCELLED', 'CANCELLED'), ('MISSING_ORDER', 'MISSING_ORDER'), ('MISSING_INVOICE', 'MISSING_INVOICE'), ('MISSING_ACCOUNTING', 'MISSING_ACCOUNTING'), ('AMBIGUOUS_ORDER', 'AMBIGUOUS_ORDER'), ('AMBIGUOUS_INVOICE', 'AMBIGUOUS_INVOICE'), ('AMBIGUOUS_ACCOUNTING', 'AMBIGUOUS_ACCOUNTING')], db_index=True, max_length=30)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('matched_by_json', models.JSONField(default=list)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('order_key', models.CharField(db_index=True, max_length=500)),
                ('invoice_key', models.CharField(blank=True, db_index=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_invoice_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='reports.reconciliationdeliveryinvoicelink')),
                ('invoice_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='reports.reconciliationinvoiceheader')),
            ],
            options={
                'db_table': 'rec_match',
                'ordering': ['order_key', 'invoice_key'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatchAccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_method', models.CharField(default='EXACT_DOCUMENT_COMPANY', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_links', to='reports.reconciliationaccountingentry')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_links', to='reports.reconciliationmatch')),
            ],
            options={
                'db_table': 'rec_match_accounting_entry',
                'ordering': ['match', 'accounting_entry'],
            },
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='accounting_entries',
            field=models.ManyToManyField(related_name='reconciliation_matches', through='reports.ReconciliationMatchAccountingEntry', to='reports.reconciliationaccountingentry'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='reports.reconciliationorderline'),
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_version', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Completed', 'Completed'), ('Completed with Warnings', 'Completed with Warnings'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], db_index=True, default='Queued', max_length=30)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rec_run',
                'ordering': ['-created_at'],
                'permissions': [('run_reconciliation', 'Can run order and revenue reconciliation'), ('review_reconciliation', 'Can review reconciliation exceptions')],
            },
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='reports.reconciliationrun'),
        ),
        migrations.CreateModel(
            name='ReconciliationSourceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('ORDERS', 'ORDERS'), ('DELIVERY_INVOICE', 'DELIVERY_INVOICE'), ('INVOICES', 'INVOICES'), ('ACCOUNTING_REVENUE', 'ACCOUNTING_REVENUE')], db_index=True, max_length=30)),
                ('source_name', models.CharField(max_length=255)),
                ('source_version', models.CharField(db_index=True, max_length=160)),
                ('status', models.CharField(choices=[('Loading', 'Loading'), ('Ready', 'Ready'), ('Ready with Warnings', 'Ready with Warnings'), ('Failed', 'Failed'), ('Superseded', 'Superseded')], db_index=True, default='Loading', max_length=30)),
                ('extracted_at', models.DateTimeField()),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rec_source_snapshot',
                'ordering': ['-extracted_at', 'source_kind'],
                'constraints': [models.UniqueConstraint(fields=('source_kind', 'source_name', 'source_version'), name='rec_unique_source_version')],
            },
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='accounting_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_reconciliation_runs', to='reports.reconciliationsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='invoice_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_reconciliation_runs', to='reports.reconciliationsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='link_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_reconciliation_runs', to='reports.reconciliationsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='order_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_reconciliation_runs', to='reports.reconciliationsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='reconciliationorderline',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='reports.reconciliationsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='reconciliationinvoiceheader',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_headers', to='reports.reconciliationsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='reconciliationdeliveryinvoicelink',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_invoice_links', to='reports.reconciliationsourcesnapshot'),
        ),
        migrations.AddField(
            model_name='reconciliationaccountingentry',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_entries', to='reports.reconciliationsourcesnapshot'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationmatchaccountingentry',
            constraint=models.UniqueConstraint(fields=('match', 'accounting_entry'), name='rec_unique_match_accounting_entry'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['run', 'status'], name='rec_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationmatch',
            constraint=models.UniqueConstraint(fields=('run', 'delivery_invoice_link'), name='rec_unique_run_link_match'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.UniqueConstraint(fields=('order_snapshot', 'link_snapshot', 'invoice_snapshot', 'accounting_snapshot', 'rule_version'), name='rec_unique_run_contract'),
        ),
        migrations.AddIndex(
            model_name='reconciliationorderline',
            index=models.Index(fields=['snapshot', 'company_code', 'branch_code', 'order_number', 'line_number'], name='rec_order_business_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationorderline',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_record_id'), name='rec_unique_order_source_row'),
        ),
        migrations.AddIndex(
            model_name='reconciliationinvoiceheader',
            index=models.Index(fields=['snapshot', 'company_code', 'branch_code', 'invoice_number'], name='rec_invoice_business_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationinvoiceheader',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_record_id'), name='rec_unique_invoice_source_row'),
        ),
        migrations.AddIndex(
            model_name='reconciliationdeliveryinvoicelink',
            index=models.Index(fields=['snapshot', 'company_code', 'order_branch_code', 'order_number', 'line_number'], name='rec_link_order_key_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationdeliveryinvoicelink',
            index=models.Index(fields=['snapshot', 'company_code', 'invoice_branch_code', 'invoice_number'], name='rec_link_invoice_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationdeliveryinvoicelink',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_record_id'), name='rec_unique_link_source_row'),
        ),
        migrations.AddIndex(
            model_name='reconciliationaccountingentry',
            index=models.Index(fields=['snapshot', 'company_code', 'document_number'], name='rec_accounting_doc_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationaccountingentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_record_id'), name='rec_unique_accounting_source_row'),
        ),
    ]
