# Generated by Django 6.0.6 on 2026-09-07 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0123_reconciliation_ca_orders_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationBufferSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Completed', 'Completed'), ('Completed with Warnings', 'Completed with Warnings'), ('Failed', 'Failed')], db_index=True, default='Queued', max_length=30)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('stage_code', models.CharField(default='queued', max_length=60)),
                ('stage_label', models.CharField(default='Waiting for semantic-model synchronization', max_length=255)),
                ('source_status_json', models.JSONField(blank=True, default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_buffer_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rec_buffer_sync_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
