# Generated by Django 6.0.6 on 2026-09-13 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0136_machine_sales_dimensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentReferenceImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Completed with Warnings', 'Completed with Warnings'), ('Failed', 'Failed')], db_index=True, default='Running', max_length=30)),
                ('asset_source_name', models.CharField(max_length=255)),
                ('asset_source_hash', models.CharField(blank=True, max_length=64)),
                ('prefix_source_name', models.CharField(max_length=255)),
                ('prefix_source_hash', models.CharField(blank=True, max_length=64)),
                ('serial_records_read', models.PositiveIntegerField(default=0)),
                ('prefix_records_read', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_unchanged', models.PositiveIntegerField(default=0)),
                ('records_deactivated', models.PositiveIntegerField(default=0)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_reference_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment_reference_import_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPrefixModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=120)),
                ('prefix', models.CharField(db_index=True, max_length=20)),
                ('model', models.CharField(db_index=True, max_length=255)),
                ('parent_product_family', models.CharField(blank=True, db_index=True, max_length=255)),
                ('product_family', models.CharField(blank=True, max_length=255)),
                ('equipment_type', models.CharField(blank=True, max_length=255)),
                ('source_created_by', models.CharField(blank=True, max_length=255)),
                ('ambiguous_prefix', models.BooleanField(db_index=True, default=False)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_last_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefix_references', to='reports.equipmentreferenceimportrun')),
            ],
            options={
                'db_table': 'equipment_prefix_model_reference',
                'ordering': ['prefix', 'model'],
                'indexes': [models.Index(fields=['active', 'prefix', 'ambiguous_prefix'], name='equip_prefix_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('brand', 'prefix', 'model', 'parent_product_family', 'product_family'), name='equip_unique_prefix_model')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSerialReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('serial_prefix', models.CharField(blank=True, db_index=True, max_length=20)),
                ('make', models.CharField(blank=True, db_index=True, max_length=120)),
                ('model', models.CharField(blank=True, db_index=True, max_length=255)),
                ('product_family', models.CharField(blank=True, db_index=True, max_length=255)),
                ('dealer_customer_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('ownership_status', models.CharField(blank=True, max_length=80)),
                ('model_year', models.CharField(blank=True, max_length=20)),
                ('subscription_status', models.CharField(blank=True, max_length=80)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_last_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_references', to='reports.equipmentreferenceimportrun')),
            ],
            options={
                'db_table': 'equipment_serial_reference',
                'ordering': ['serial_number'],
                'indexes': [models.Index(fields=['active', 'serial_prefix'], name='equip_serial_prefix_idx'), models.Index(fields=['active', 'make', 'model'], name='equip_serial_model_idx')],
            },
        ),
    ]
