# Generated by Django 6.0.6 on 2026-09-13 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0137_equipment_reference_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentreferenceimportrun',
            name='model_records_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentreferenceimportrun',
            name='model_source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='equipmentreferenceimportrun',
            name='model_source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipmentreferenceimportrun',
            name='product_group_records_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentreferenceimportrun',
            name='product_group_source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='equipmentreferenceimportrun',
            name='product_group_source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='EquipmentProductGroupReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('source_created_by', models.CharField(blank=True, max_length=255)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_last_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_groups', to='reports.equipmentreferenceimportrun')),
            ],
            options={
                'db_table': 'equipment_product_group_reference',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=80, unique=True)),
                ('model', models.CharField(db_index=True, max_length=255)),
                ('normalized_model', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=120)),
                ('family', models.CharField(blank=True, db_index=True, max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('equipment_type', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_status', models.CharField(blank=True, max_length=40)),
                ('source_created_by', models.CharField(blank=True, max_length=255)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_last_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_references', to='reports.equipmentreferenceimportrun')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='reports.equipmentproductgroupreference')),
            ],
            options={
                'db_table': 'equipment_model_reference',
                'ordering': ['priority', 'brand', 'model'],
                'indexes': [models.Index(fields=['active', 'brand', 'normalized_model'], name='equip_model_lookup_idx'), models.Index(fields=['active', 'product_group'], name='equip_model_group_idx')],
            },
        ),
    ]
