# Generated by Django 6.0.6 on 2026-09-13 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0138_equipment_model_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsMajorClassReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parts_major_class_reference',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PartsClassificationImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Completed with Warnings', 'Completed with Warnings'), ('Failed', 'Failed')], db_index=True, default='Running', max_length=30)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_file_hash', models.CharField(blank=True, max_length=64)),
                ('source_sheets_json', models.JSONField(blank=True, default=list)),
                ('records_read', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_unchanged', models.PositiveIntegerField(default=0)),
                ('records_deactivated', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('major_class_counts_json', models.JSONField(blank=True, default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_classification_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parts_classification_import_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PartClassificationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=160)),
                ('normalized_part_number', models.CharField(max_length=160, unique=True)),
                ('minor_class', models.CharField(blank=True, db_index=True, max_length=20)),
                ('ppc', models.CharField(blank=True, db_index=True, max_length=40)),
                ('classification_status', models.CharField(choices=[('Classified', 'Classified'), ('Conflict', 'Conflict')], db_index=True, default='Classified', max_length=20)),
                ('conflict_variants_json', models.JSONField(blank=True, default=list)),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_last_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='reports.partsclassificationimportrun')),
                ('major_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='reports.partsmajorclassreference')),
            ],
            options={
                'db_table': 'part_classification_reference',
                'ordering': ['normalized_part_number'],
                'indexes': [models.Index(fields=['active', 'classification_status', 'major_class'], name='part_class_major_idx'), models.Index(fields=['active', 'minor_class', 'ppc'], name='part_minor_ppc_idx')],
            },
        ),
    ]
