# Generated by Django 6.0.6 on 2026-09-13 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0139_parts_classification_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsSalesSynchronizationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Completed with Warnings', 'Completed with Warnings'), ('Failed', 'Failed')], db_index=True, default='Running', max_length=30)),
                ('data_through_date', models.DateField(blank=True, db_index=True, null=True)),
                ('records_read', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_unchanged', models.PositiveIntegerField(default=0)),
                ('records_deactivated', models.PositiveIntegerField(default=0)),
                ('classified_records', models.PositiveIntegerField(default=0)),
                ('allocated_revenue_eur', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts_sales_runs', to='reports.reconciliationrun')),
            ],
            options={
                'db_table': 'bcc_parts_sales_sync_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PartSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(max_length=255, unique=True)),
                ('business_date', models.DateField(db_index=True)),
                ('company_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('branch_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=160)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=160)),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=160)),
                ('normalized_part_number', models.CharField(blank=True, db_index=True, max_length=160)),
                ('major_class_code', models.CharField(blank=True, db_index=True, max_length=4)),
                ('major_class_description', models.CharField(blank=True, max_length=255)),
                ('minor_class', models.CharField(blank=True, db_index=True, max_length=20)),
                ('ppc', models.CharField(blank=True, db_index=True, max_length=40)),
                ('classification_status', models.CharField(db_index=True, default='Not Classified', max_length=30)),
                ('invoiced_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('source_line_amount', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('allocated_revenue_eur', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_last_seen_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synchronization_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='reports.partssalessynchronizationrun')),
            ],
            options={
                'db_table': 'bcc_part_sale_detail',
                'ordering': ['-business_date', 'invoice_number', 'part_number'],
                'indexes': [models.Index(fields=['active', 'business_date'], name='bcc_part_sale_date_idx'), models.Index(fields=['active', 'major_class_code'], name='bcc_part_sale_major_idx'), models.Index(fields=['active', 'customer_code'], name='bcc_part_sale_customer_idx')],
            },
        ),
    ]
