# Generated by Django 6.0.6 on 2026-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0140_parts_sales_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsaledetail',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partsaledetail',
            name='brand_group',
            field=models.CharField(db_index=True, default='Brand Not Available', max_length=40),
        ),
        migrations.AddField(
            model_name='reconciliationorderline',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
