# Generated by Django 6.0.6 on 2026-09-19 14:24

from django.db import migrations


def remove_obsolete_permissions(apps, schema_editor):
    # Delete only content types owned by the retired catalogue. Django cascades
    # their permissions and assignments; permissions for retained products remain.
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.using(schema_editor.connection.alias).filter(
        app_label='reports', model__in=[
            'aiprovider', 'aiprovidercredential', 'aiprovidermodel',
            'aiusecaseconfiguration', 'aiagentproviderconfiguration',
            'aiproviderusagelog', 'aiproviderhealthlog',
            'aiprovidercircuitstate', 'aiproviderauditlog',
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0145_key_accounts_use_customer_country_groups'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiagentproviderconfiguration',
            name='unique_ai_agent_use_case_provider',
        ),
        migrations.RemoveField(
            model_name='aiprovider',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='aiprovider',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='aiusecaseconfiguration',
            name='primary_provider',
        ),
        migrations.RemoveField(
            model_name='aiproviderhealthlog',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='aiproviderauditlog',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='aiprovidercircuitstate',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='aiproviderauditlog',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='aiprovidercredential',
            name='unique_ai_provider_credential_type',
        ),
        migrations.RemoveConstraint(
            model_name='aiprovidermodel',
            name='unique_ai_provider_model',
        ),
        migrations.RemoveField(
            model_name='aiusecaseconfiguration',
            name='primary_model',
        ),
        migrations.RemoveIndex(
            model_name='aiproviderusagelog',
            name='ai_provider_usage_time',
        ),
        migrations.RemoveIndex(
            model_name='aiproviderusagelog',
            name='ai_use_case_usage_time',
        ),
        migrations.RemoveField(
            model_name='aiagentproviderconfiguration',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='aiagentproviderconfiguration',
            name='model',
        ),
        migrations.RemoveField(
            model_name='aiagentproviderconfiguration',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='aiagentproviderconfiguration',
            name='use_case',
        ),
        migrations.DeleteModel(
            name='AIProviderHealthLog',
        ),
        migrations.DeleteModel(
            name='AIProviderCircuitState',
        ),
        migrations.DeleteModel(
            name='AIProviderAuditLog',
        ),
        migrations.RemoveField(
            model_name='aiprovidercredential',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='aiprovidermodel',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='aiproviderusagelog',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='aiproviderusagelog',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='aiproviderusagelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIAgentProviderConfiguration',
        ),
        migrations.DeleteModel(
            name='AIUseCaseConfiguration',
        ),
        migrations.DeleteModel(
            name='AIProviderCredential',
        ),
        migrations.DeleteModel(
            name='AIProviderModel',
        ),
        migrations.DeleteModel(
            name='AIProvider',
        ),
        migrations.DeleteModel(
            name='AIProviderUsageLog',
        ),
        migrations.RunPython(remove_obsolete_permissions, migrations.RunPython.noop),
    ]
