# Generated by Django 6.0.6 on 2026-09-19 15:25

from django.db import migrations


def remove_obsolete_permissions(apps, schema_editor):
    apps.get_model('contenttypes', 'ContentType').objects.using(schema_editor.connection.alias).filter(
        app_label='reports', model__in=[
            'openaibudget', 'openaicostsnapshot', 'openaicreditsnapshot',
            'openaimodelpricing', 'openaiusagelog', 'openaiusagesnapshot',
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0146_remove_api_management'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenAIBudget',
        ),
        migrations.RemoveConstraint(
            model_name='openaicostsnapshot',
            name='unique_openai_cost_snapshot',
        ),
        migrations.DeleteModel(
            name='OpenAICostSnapshot',
        ),
        migrations.DeleteModel(
            name='OpenAICreditSnapshot',
        ),
        migrations.RemoveConstraint(
            model_name='openaimodelpricing',
            name='unique_openai_model_price_period',
        ),
        migrations.DeleteModel(
            name='OpenAIModelPricing',
        ),
        migrations.RemoveIndex(
            model_name='openaiusagelog',
            name='openai_usage_time_model',
        ),
        migrations.RemoveIndex(
            model_name='openaiusagelog',
            name='openai_usage_time_section',
        ),
        migrations.RemoveField(
            model_name='voicetranscriptionlog',
            name='openai_usage_log',
        ),
        migrations.RemoveConstraint(
            model_name='openaiusagesnapshot',
            name='unique_openai_usage_snapshot',
        ),
        migrations.DeleteModel(
            name='OpenAIUsageSnapshot',
        ),
        migrations.DeleteModel(
            name='OpenAIUsageLog',
        ),
        migrations.RunPython(remove_obsolete_permissions, migrations.RunPython.noop),
    ]
