"""
Django settings for Mining360IA project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEVELOPMENT_SECRET_KEY = 'django-insecure-(*etlk@3g+09mk4!52367h16lxq(a8b#*i)s2w-t_-vjm4u!-z'
SECRET_KEY = os.getenv('MINING360_SECRET_KEY', DEVELOPMENT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('MINING360_DEBUG', '1').strip().lower() in {'1', 'true', 'yes', 'on'}

if not DEBUG and SECRET_KEY == DEVELOPMENT_SECRET_KEY:
    raise ImproperlyConfigured('MINING360_SECRET_KEY is required outside development.')

ALLOWED_HOSTS = [
    value.strip()
    for value in os.getenv(
        'MINING360_ALLOWED_HOSTS',
        '127.0.0.1,localhost,testserver,bodefm,mining360-dev.neemba.local',
    ).split(',')
    if value.strip()
]

CSRF_TRUSTED_ORIGINS = [
    value.strip()
    for value in os.getenv('MINING360_CSRF_TRUSTED_ORIGINS', '').split(',')
    if value.strip()
]

# IIS terminates HTTP/S and forwards the original request metadata to Waitress.
USE_X_FORWARDED_HOST = os.getenv(
    'MINING360_USE_X_FORWARDED_HOST',
    '0',
).strip().lower() in {'1', 'true', 'yes', 'on'}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


def _environment_boolean(name: str, default: bool) -> bool:
    fallback = '1' if default else '0'
    return os.getenv(name, fallback).strip().lower() in {'1', 'true', 'yes', 'on'}


# Production is served through the corporate HTTPS reverse proxy. Keep every
# setting environment-controlled so a staged rollout can lower HSTS or disable
# Django's redirect only when the proxy owns that responsibility explicitly.
SECURE_SSL_REDIRECT = _environment_boolean('MINING360_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = _environment_boolean('MINING360_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _environment_boolean('MINING360_CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
MINING360_REMEMBER_SESSION_SECONDS = int(
    os.getenv('MINING360_REMEMBER_SESSION_SECONDS', str(14 * 24 * 60 * 60))
)
ENABLE_USERS_PAGE_REDESIGN = os.getenv('ENABLE_USERS_PAGE_REDESIGN', 'Production')
SECURE_HSTS_SECONDS = int(os.getenv('MINING360_SECURE_HSTS_SECONDS', '3600' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _environment_boolean(
    'MINING360_SECURE_HSTS_INCLUDE_SUBDOMAINS', False
)
SECURE_HSTS_PRELOAD = _environment_boolean('MINING360_SECURE_HSTS_PRELOAD', False)
SECURE_REFERRER_POLICY = 'same-origin'


# Application definition

INSTALLED_APPS = [
    'deployment',
    'reports',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'reports.openai_usage_context.OpenAIUsageContextMiddleware',
    'reports.middleware.PlatformLoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'reports.sqlserver_config_middleware.SQLServerConfigSyncMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Mining360IA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mining360IA.wsgi.application'


# Database
# Production uses SQL Server as the single application database. SQLite is kept
# only behind an explicit development/migration switch so the existing database
# can be transferred safely before it is archived.

DATABASE_ENGINE = os.getenv('MINING360_DATABASE_ENGINE', 'sqlite').strip().lower()

if not DEBUG and DATABASE_ENGINE not in {'mssql', 'sqlserver', 'sql_server'}:
    raise ImproperlyConfigured(
        'Production requires MINING360_DATABASE_ENGINE=mssql; SQLite is development-only.'
    )


def _required_environment(name: str, fallback: str = '') -> str:
    value = os.getenv(name, fallback).strip()
    if not value:
        raise ImproperlyConfigured(f'{name} is required for the SQL Server database.')
    return value


if DATABASE_ENGINE in {'mssql', 'sqlserver', 'sql_server'}:
    database_name = os.getenv('MINING360_APP_SQL_DATABASE', 'Mining360App').strip()
    database_host = _required_environment(
        'MINING360_APP_SQL_SERVER',
        os.getenv('MINING360_SQL_SERVER', ''),
    )
    database_user = os.getenv(
        'MINING360_APP_SQL_USER',
        os.getenv('MINING360_SQL_USER', ''),
    ).strip()
    database_password = os.getenv(
        'MINING360_APP_SQL_PASSWORD',
        os.getenv('MINING360_SQL_PASSWORD', ''),
    )
    database_options = {
        'driver': os.getenv(
            'MINING360_APP_SQL_DRIVER',
            os.getenv('MINING360_SQL_DRIVER', 'ODBC Driver 18 for SQL Server'),
        ),
        'extra_params': os.getenv(
            'MINING360_APP_SQL_EXTRA_PARAMS',
            'Encrypt=optional;TrustServerCertificate=yes;Connection Timeout=15',
        ),
    }
    if not database_user:
        database_options['trusted_connection'] = 'yes'
    elif not database_password:
        raise ImproperlyConfigured(
            'MINING360_APP_SQL_PASSWORD is required when SQL authentication is used.'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': database_name,
            'HOST': database_host,
            'PORT': os.getenv(
                'MINING360_APP_SQL_PORT',
                os.getenv('MINING360_SQL_PORT', '1433'),
            ),
            'USER': database_user,
            'PASSWORD': database_password,
            'OPTIONS': database_options,
            'CONN_MAX_AGE': int(os.getenv('MINING360_DB_CONN_MAX_AGE', '60')),
        },
    }
    DATABASE_CONNECTION_POOLING = False
    os.environ.setdefault('MINING360_SQL_CONFIG_STORE', '0')
    MIDDLEWARE = [
        item
        for item in MIDDLEWARE
        if item != 'reports.sqlserver_config_middleware.SQLServerConfigSyncMiddleware'
    ]
else:
    if DATABASE_ENGINE != 'sqlite':
        raise ImproperlyConfigured(
            'MINING360_DATABASE_ENGINE must be mssql or sqlite.'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(os.getenv('MINING360_SQLITE_PATH', BASE_DIR / 'db.sqlite3')),
            'OPTIONS': {
                'timeout': 30,
                'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL',
            },
        },
    }

legacy_sqlite_path = os.getenv('MINING360_LEGACY_SQLITE_PATH', '').strip()
if legacy_sqlite_path:
    DATABASES['legacy_sqlite'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(legacy_sqlite_path),
        'OPTIONS': {'timeout': 30},
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'reports.active_directory_backend.ActiveDirectoryBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Atlantic/Reykjavik'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.getenv('MINING360_STATIC_ROOT', BASE_DIR / 'staticfiles'))
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
AZURE_AD_REDIRECT_URI = os.getenv('AZURE_AD_REDIRECT_URI', '').strip()

ENABLE_PERSISTENT_CONVERSATIONS = os.getenv('ENABLE_PERSISTENT_CONVERSATIONS', 'true').lower() in {'1', 'true', 'yes', 'on'}
ENABLE_CONVERSATION_ARCHIVE = os.getenv('ENABLE_CONVERSATION_ARCHIVE', 'true').lower() in {'1', 'true', 'yes', 'on'}
ENABLE_CONVERSATION_RENAME = os.getenv('ENABLE_CONVERSATION_RENAME', 'true').lower() in {'1', 'true', 'yes', 'on'}
ENABLE_CONVERSATION_ARTIFACTS = os.getenv('ENABLE_CONVERSATION_ARTIFACTS', 'true').lower() in {'1', 'true', 'yes', 'on'}
ENABLE_ADAPTIVE_PERFORMANCE_RESPONSES = os.getenv('ENABLE_ADAPTIVE_PERFORMANCE_RESPONSES', 'Production').strip()
ENABLE_CONVERSATIONAL_FOLLOW_UP_RESOLUTION = os.getenv(
    'ENABLE_CONVERSATIONAL_FOLLOW_UP_RESOLUTION', 'Production'
).strip()
ENABLE_USER_OWNS_DATA_EMBEDDING = os.getenv(
    'ENABLE_USER_OWNS_DATA_EMBEDDING', 'Production'
).strip()
ENABLE_PRIME_MOVERS_POWERAPPS_EMBEDDING = os.getenv(
    'ENABLE_PRIME_MOVERS_POWERAPPS_EMBEDDING', 'Production'
).strip()
ENABLE_ENTRA_ACCOUNT_LINKING = os.getenv(
    'ENABLE_ENTRA_ACCOUNT_LINKING', 'Production'
).strip()
ENABLE_DELEGATED_TOKEN_REFRESH = os.getenv(
    'ENABLE_DELEGATED_TOKEN_REFRESH', 'Production'
).strip()
FOLLOW_UP_MINIMUM_CONFIDENCE = int(os.getenv('FOLLOW_UP_MINIMUM_CONFIDENCE', '85'))
MAX_ACTIVE_CONVERSATIONS_PER_USER = int(os.getenv('MAX_ACTIVE_CONVERSATIONS_PER_USER', '10'))

ENABLE_DOWNTIME_MAPPING_CHECK = os.getenv('ENABLE_DOWNTIME_MAPPING_CHECK', 'Admin Only').strip()
ENABLE_FULL_AI_DOWNTIME_AUDIT = os.getenv('ENABLE_FULL_AI_DOWNTIME_AUDIT', 'Pilot').strip()
ENABLE_DOWNTIME_MAPPING_WRITEBACK = os.getenv('ENABLE_DOWNTIME_MAPPING_WRITEBACK', 'Disabled').strip()
ENABLE_DOWNTIME_MAPPING_BATCH_PROCESSING = os.getenv('ENABLE_DOWNTIME_MAPPING_BATCH_PROCESSING', 'Pilot').strip()
ENABLE_DOWNTIME_MAPPING_KNOWLEDGE_LEARNING = os.getenv('ENABLE_DOWNTIME_MAPPING_KNOWLEDGE_LEARNING', 'Admin Only').strip()
DOWNTIME_MAPPING_VERIFIED_THRESHOLD = int(os.getenv('DOWNTIME_MAPPING_VERIFIED_THRESHOLD', '90'))
DOWNTIME_MAPPING_MISMATCH_THRESHOLD = int(os.getenv('DOWNTIME_MAPPING_MISMATCH_THRESHOLD', '85'))
DOWNTIME_MAPPING_REVIEW_THRESHOLD = int(os.getenv('DOWNTIME_MAPPING_REVIEW_THRESHOLD', '70'))
DOWNTIME_MAPPING_MAX_DATE_RANGE_DAYS = int(os.getenv('DOWNTIME_MAPPING_MAX_DATE_RANGE_DAYS', '92'))
DOWNTIME_MAPPING_MAX_ROWS_PER_RUN = int(os.getenv('DOWNTIME_MAPPING_MAX_ROWS_PER_RUN', '5000'))
DOWNTIME_MAPPING_MAX_ESTIMATED_COST = float(os.getenv('DOWNTIME_MAPPING_MAX_ESTIMATED_COST', '20'))
DOWNTIME_MAPPING_DEV_THREAD_WORKER = os.getenv('DOWNTIME_MAPPING_DEV_THREAD_WORKER', 'true').lower() in {'1', 'true', 'yes', 'on'}
