"""
Django settings for Mining360IA project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEVELOPMENT_SECRET_KEY = 'django-insecure-(*etlk@3g+09mk4!52367h16lxq(a8b#*i)s2w-t_-vjm4u!-z'
SECRET_KEY = os.getenv('MINING360_SECRET_KEY', DEVELOPMENT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('MINING360_DEBUG', '1').strip().lower() in {'1', 'true', 'yes', 'on'}

if not DEBUG and SECRET_KEY == DEVELOPMENT_SECRET_KEY:
    raise ImproperlyConfigured('MINING360_SECRET_KEY is required outside development.')

ALLOWED_HOSTS = [
    value.strip()
    for value in os.getenv(
        'MINING360_ALLOWED_HOSTS',
        '127.0.0.1,localhost,testserver,bodefm,mining360-dev.neemba.local',
    ).split(',')
    if value.strip()
]

MINING360_PUBLIC_BASE_URL = os.getenv('MINING360_PUBLIC_BASE_URL', '').strip().rstrip('/')
CSRF_TRUSTED_ORIGINS = [
    value.strip()
    for value in os.getenv('MINING360_CSRF_TRUSTED_ORIGINS', '').split(',')
    if value.strip()
]
if MINING360_PUBLIC_BASE_URL.startswith(('https://', 'http://')):
    CSRF_TRUSTED_ORIGINS.append(MINING360_PUBLIC_BASE_URL)
CSRF_TRUSTED_ORIGINS.extend(
    f'https://{host}'
    for host in ALLOWED_HOSTS
    if host.endswith('.neemba.local')
)
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# IIS terminates HTTP/S and forwards the original request metadata to Waitress.
USE_X_FORWARDED_HOST = os.getenv(
    'MINING360_USE_X_FORWARDED_HOST',
    '0',
).strip().lower() in {'1', 'true', 'yes', 'on'}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


def _environment_boolean(name: str, default: bool) -> bool:
    fallback = '1' if default else '0'
    return os.getenv(name, fallback).strip().lower() in {'1', 'true', 'yes', 'on'}


# Production is served through the corporate HTTPS reverse proxy. Keep every
# setting environment-controlled so a staged rollout can lower HSTS or disable
# Django's redirect only when the proxy owns that responsibility explicitly.
SECURE_SSL_REDIRECT = _environment_boolean('MINING360_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = _environment_boolean('MINING360_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _environment_boolean('MINING360_CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
MINING360_REMEMBER_SESSION_SECONDS = int(
    os.getenv('MINING360_REMEMBER_SESSION_SECONDS', str(14 * 24 * 60 * 60))
)
ENABLE_USERS_PAGE_REDESIGN = os.getenv('ENABLE_USERS_PAGE_REDESIGN', 'Production')
SECURE_HSTS_SECONDS = int(os.getenv('MINING360_SECURE_HSTS_SECONDS', '3600' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _environment_boolean(
    'MINING360_SECURE_HSTS_INCLUDE_SUBDOMAINS', False
)
SECURE_HSTS_PRELOAD = _environment_boolean('MINING360_SECURE_HSTS_PRELOAD', False)
SECURE_REFERRER_POLICY = 'same-origin'


# Application definition

INSTALLED_APPS = [
    'deployment',
    'reports',
    'codex_chatbot',
    'codex_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Independent Codex modules remain unavailable until explicitly enabled.
ENABLE_CODEX_CHATBOT = os.getenv('ENABLE_CODEX_CHATBOT', 'Disabled')
ENABLE_CODEX_ADMIN = os.getenv('ENABLE_CODEX_ADMIN', 'Disabled')
CODEX_CHATBOT_APP_SERVER_ENABLED = _environment_boolean(
    'CODEX_CHATBOT_APP_SERVER_ENABLED', False
)
CODEX_CHATBOT_CLI_PATH = os.getenv('CODEX_CHATBOT_CLI_PATH', '').strip()
CODEX_CHATBOT_HOME = os.getenv(
    'CODEX_CHATBOT_HOME', str(BASE_DIR / '.test-runtime' / 'codex-chatbot-home')
)
CODEX_CHATBOT_WORKSPACE = os.getenv(
    'CODEX_CHATBOT_WORKSPACE', str(BASE_DIR / '.test-runtime' / 'codex-chatbot-workspace')
)
CODEX_CHATBOT_TIMEOUT_SECONDS = int(os.getenv('CODEX_CHATBOT_TIMEOUT_SECONDS', '45'))
CODEX_CHATBOT_GENERAL_TIMEOUT_SECONDS = int(os.getenv('CODEX_CHATBOT_GENERAL_TIMEOUT_SECONDS', '120'))
CODEX_CHATBOT_ARTIFACT_ROOT = os.getenv(
    'CODEX_CHATBOT_ARTIFACT_ROOT', str(BASE_DIR / '.test-runtime' / 'codex-chatbot-artifacts')
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'reports.security_headers.Mining360ContentSecurityPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'reports.openai_usage_context.OpenAIUsageContextMiddleware',
    'reports.middleware.PlatformLoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'reports.sqlserver_config_middleware.SQLServerConfigSyncMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Mining360IA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mining360IA.wsgi.application'


# Database
# Production uses SQL Server as the single application database. SQLite is kept
# only behind an explicit development/migration switch so the existing database
# can be transferred safely before it is archived.

DATABASE_ENGINE = os.getenv('MINING360_DATABASE_ENGINE', 'sqlite').strip().lower()

if not DEBUG and DATABASE_ENGINE not in {'mssql', 'sqlserver', 'sql_server'}:
    raise ImproperlyConfigured(
        'Production requires MINING360_DATABASE_ENGINE=mssql; SQLite is development-only.'
    )


def _required_environment(name: str, fallback: str = '') -> str:
    value = os.getenv(name, fallback).strip()
    if not value:
        raise ImproperlyConfigured(f'{name} is required for the SQL Server database.')
    return value


if DATABASE_ENGINE in {'mssql', 'sqlserver', 'sql_server'}:
    database_name = os.getenv('MINING360_APP_SQL_DATABASE', 'Mining360App').strip()
    database_host = _required_environment(
        'MINING360_APP_SQL_SERVER',
        os.getenv('MINING360_SQL_SERVER', ''),
    )
    database_user = os.getenv(
        'MINING360_APP_SQL_USER',
        os.getenv('MINING360_SQL_USER', ''),
    ).strip()
    database_password = os.getenv(
        'MINING360_APP_SQL_PASSWORD',
        os.getenv('MINING360_SQL_PASSWORD', ''),
    )
    database_options = {
        'driver': os.getenv(
            'MINING360_APP_SQL_DRIVER',
            os.getenv('MINING360_SQL_DRIVER', 'ODBC Driver 18 for SQL Server'),
        ),
        'extra_params': os.getenv(
            'MINING360_APP_SQL_EXTRA_PARAMS',
            'Encrypt=optional;TrustServerCertificate=yes;Connection Timeout=15',
        ),
    }
    if not database_user:
        database_options['trusted_connection'] = 'yes'
    elif not database_password:
        raise ImproperlyConfigured(
            'MINING360_APP_SQL_PASSWORD is required when SQL authentication is used.'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': database_name,
            'HOST': database_host,
            'PORT': os.getenv(
                'MINING360_APP_SQL_PORT',
                os.getenv('MINING360_SQL_PORT', '1433'),
            ),
            'USER': database_user,
            'PASSWORD': database_password,
            'OPTIONS': database_options,
            'CONN_MAX_AGE': int(os.getenv('MINING360_DB_CONN_MAX_AGE', '60')),
        },
    }
    DATABASE_CONNECTION_POOLING = False
    os.environ.setdefault('MINING360_SQL_CONFIG_STORE', '0')
    MIDDLEWARE = [
        item
        for item in MIDDLEWARE
        if item != 'reports.sqlserver_config_middleware.SQLServerConfigSyncMiddleware'
    ]
else:
    if DATABASE_ENGINE != 'sqlite':
        raise ImproperlyConfigured(
            'MINING360_DATABASE_ENGINE must be mssql or sqlite.'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(os.getenv('MINING360_SQLITE_PATH', BASE_DIR / 'db.sqlite3')),
            'OPTIONS': {
                'timeout': 30,
                'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL',
            },
        },
    }

legacy_sqlite_path = os.getenv('MINING360_LEGACY_SQLITE_PATH', '').strip()
if legacy_sqlite_path:
    DATABASES['legacy_sqlite'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(legacy_sqlite_path),
        'OPTIONS': {'timeout': 30},
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'reports.active_directory_backend.ActiveDirectoryBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Atlantic/Reykjavik'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.getenv('MINING360_STATIC_ROOT', BASE_DIR / 'staticfiles'))
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('MINING360_MEDIA_ROOT', BASE_DIR / 'media'))
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
AZURE_AD_REDIRECT_URI = os.getenv('AZURE_AD_REDIRECT_URI', '').strip()

ENABLE_PERSISTENT_CONVERSATIONS = os.getenv('ENABLE_PERSISTENT_CONVERSATIONS', 'true').lower() in {'1', 'true', 'yes', 'on'}
ENABLE_CONVERSATION_ARCHIVE = os.getenv('ENABLE_CONVERSATION_ARCHIVE', 'true').lower() in {'1', 'true', 'yes', 'on'}
ENABLE_CONVERSATION_RENAME = os.getenv('ENABLE_CONVERSATION_RENAME', 'true').lower() in {'1', 'true', 'yes', 'on'}
ENABLE_CONVERSATION_ARTIFACTS = os.getenv('ENABLE_CONVERSATION_ARTIFACTS', 'true').lower() in {'1', 'true', 'yes', 'on'}
ENABLE_ADAPTIVE_PERFORMANCE_RESPONSES = os.getenv('ENABLE_ADAPTIVE_PERFORMANCE_RESPONSES', 'Production').strip()
ENABLE_AVAILABILITY_COMMAND_CENTER_HOME = os.getenv(
    'ENABLE_AVAILABILITY_COMMAND_CENTER_HOME', 'Admin Only'
).strip()
ENABLE_PREMIUM_REPORTING_HUB = os.getenv('ENABLE_PREMIUM_REPORTING_HUB', 'Production').strip()
ENABLE_REPORTING_CONFIGURATION_WORKSPACE = os.getenv(
    'ENABLE_REPORTING_CONFIGURATION_WORKSPACE', 'Production'
).strip()
ENABLE_AI_CONFIG_WORKSPACE_REDESIGN = os.getenv(
    'ENABLE_AI_CONFIG_WORKSPACE_REDESIGN', 'Production'
).strip()
ENABLE_REPORT_CARD_PERSONALIZATION = os.getenv(
    'ENABLE_REPORT_CARD_PERSONALIZATION', 'Production'
).strip()
ENABLE_PREMIUM_GENERIC_REPORT_VIEWER = os.getenv(
    'ENABLE_PREMIUM_GENERIC_REPORT_VIEWER', 'Production'
).strip()
ENABLE_STABLE_POWERBI_VIEWER_RUNTIME = os.getenv(
    'ENABLE_STABLE_POWERBI_VIEWER_RUNTIME', 'Production'
).strip()
ENABLE_FLEET_INVENTORY_CHAT = os.getenv('ENABLE_FLEET_INVENTORY_CHAT', 'Admin Only').strip()
ENABLE_FLEET_EXCEL_EXPORT = os.getenv('ENABLE_FLEET_EXCEL_EXPORT', 'Admin Only').strip()
ENABLE_EQUIPMENT_SERIAL_LOOKUP = os.getenv('ENABLE_EQUIPMENT_SERIAL_LOOKUP', 'Admin Only').strip()
ENABLE_EQUIPMENT_CODE_LOOKUP = os.getenv('ENABLE_EQUIPMENT_CODE_LOOKUP', 'Pilot').strip()
ENABLE_FLEET_FUZZY_SITE_MATCHING = os.getenv('ENABLE_FLEET_FUZZY_SITE_MATCHING', 'Pilot').strip()
ENABLE_COMPLETE_FLEET_PERFORMANCE_CHAT = os.getenv('ENABLE_COMPLETE_FLEET_PERFORMANCE_CHAT', 'Admin Only').strip()
ENABLE_FLEET_PERFORMANCE_COMPARISON = os.getenv('ENABLE_FLEET_PERFORMANCE_COMPARISON', 'Admin Only').strip()
ENABLE_FLEET_PERFORMANCE_TRENDS = os.getenv('ENABLE_FLEET_PERFORMANCE_TRENDS', 'Admin Only').strip()
ENABLE_FLEET_PERFORMANCE_RANKING = os.getenv('ENABLE_FLEET_PERFORMANCE_RANKING', 'Admin Only').strip()
ENABLE_PLANNED_UNPLANNED_ANALYSIS = os.getenv('ENABLE_PLANNED_UNPLANNED_ANALYSIS', 'Admin Only').strip()
ENABLE_FLEET_PERFORMANCE_EXPORT = os.getenv('ENABLE_FLEET_PERFORMANCE_EXPORT', 'Admin Only').strip()
ENABLE_FLEET_PERFORMANCE_DIAGNOSTICS = os.getenv('ENABLE_FLEET_PERFORMANCE_DIAGNOSTICS', 'Admin Only').strip()
ENABLE_CONVERSATIONAL_FOLLOW_UP_RESOLUTION = os.getenv(
    'ENABLE_CONVERSATIONAL_FOLLOW_UP_RESOLUTION', 'Production'
).strip()
ENABLE_CHATBOT_CAPABILITY_DISCOVERY = os.getenv('ENABLE_CHATBOT_CAPABILITY_DISCOVERY', 'Admin Only').strip()
ENABLE_ANSWERABILITY_GUARD = os.getenv('ENABLE_ANSWERABILITY_GUARD', 'Admin Only').strip()
ENABLE_GROUNDED_RESPONSE_GUARD = os.getenv('ENABLE_GROUNDED_RESPONSE_GUARD', 'Admin Only').strip()
ENABLE_GRACEFUL_ABSTENTION = os.getenv('ENABLE_GRACEFUL_ABSTENTION', 'Admin Only').strip()
ENABLE_CERTIFIED_CHAT_SUGGESTIONS = os.getenv('ENABLE_CERTIFIED_CHAT_SUGGESTIONS', 'Admin Only').strip()
ENABLE_OPERATION_LEVEL_READINESS = os.getenv('ENABLE_OPERATION_LEVEL_READINESS', 'Admin Only').strip()
ENABLE_ACTION_ELIGIBILITY = os.getenv('ENABLE_ACTION_ELIGIBILITY', 'Admin Only').strip()
ENABLE_CHAT_PRODUCTION_STATE_MACHINE = os.getenv('ENABLE_CHAT_PRODUCTION_STATE_MACHINE', 'Admin Only').strip()
ENABLE_CHAT_DEPENDENCY_HEALTH = os.getenv('ENABLE_CHAT_DEPENDENCY_HEALTH', 'Admin Only').strip()
ENABLE_CHAT_READINESS_DASHBOARD = os.getenv('ENABLE_CHAT_READINESS_DASHBOARD', 'Admin Only').strip()
ENABLE_CHAT_DEAD_SUGGESTION_AUTO_HIDE = os.getenv('ENABLE_CHAT_DEAD_SUGGESTION_AUTO_HIDE', 'Admin Only').strip()
ENABLE_REAL_PILOT_COHORTS = os.getenv('ENABLE_REAL_PILOT_COHORTS', 'Production').strip()
CHAT_CERTIFICATION_ENVIRONMENT = os.getenv('CHAT_CERTIFICATION_ENVIRONMENT', 'Development').strip()
CHAT_SUGGESTION_CONFIGURATION_VERSION = os.getenv('CHAT_SUGGESTION_CONFIGURATION_VERSION', '1').strip()
ENABLE_DATA_GAP_REGISTRY = os.getenv('ENABLE_DATA_GAP_REGISTRY', 'Admin Only').strip()
ENABLE_CONTEXTUAL_CAPABILITY_HELP = os.getenv('ENABLE_CONTEXTUAL_CAPABILITY_HELP', 'Admin Only').strip()
ENABLE_BUSINESS_MAPPING_STUDIO = os.getenv('ENABLE_BUSINESS_MAPPING_STUDIO', 'Admin Only').strip()
ENABLE_BUSINESS_MAPPING_SUGGESTIONS = os.getenv('ENABLE_BUSINESS_MAPPING_SUGGESTIONS', 'Admin Only').strip()
ENABLE_BUSINESS_MAPPING_AI_ASSISTANCE = os.getenv('ENABLE_BUSINESS_MAPPING_AI_ASSISTANCE', 'Disabled').strip()
ENABLE_BUSINESS_MAPPING_BULK_VALIDATION = os.getenv('ENABLE_BUSINESS_MAPPING_BULK_VALIDATION', 'Admin Only').strip()
ENABLE_BUSINESS_MAPPING_REVENUE_ALLOCATION = os.getenv(
    'ENABLE_BUSINESS_MAPPING_REVENUE_ALLOCATION', 'Admin Only'
).strip()
ENABLE_BUSINESS_MAPPING_PUBLICATION = os.getenv('ENABLE_BUSINESS_MAPPING_PUBLICATION', 'Admin Only').strip()
ENABLE_BUSINESS_MAPPING_POWERBI_INTEGRATION = os.getenv(
    'ENABLE_BUSINESS_MAPPING_POWERBI_INTEGRATION', 'Disabled'
).strip()
ENABLE_BUSINESS_MAPPING_STUDIO_V2 = os.getenv('ENABLE_BUSINESS_MAPPING_STUDIO_V2', 'Admin Only').strip()
BUSINESS_MAPPING_AUTO_SYNC_ON_STUDIO_OPEN = os.getenv(
    'BUSINESS_MAPPING_AUTO_SYNC_ON_STUDIO_OPEN', 'true'
).lower() in {'1', 'true', 'yes', 'on'}
BUSINESS_MAPPING_AUTO_SYNC_MAX_AGE_MINUTES = max(
    1, int(os.getenv('BUSINESS_MAPPING_AUTO_SYNC_MAX_AGE_MINUTES', '15'))
)
ENABLE_BUSINESS_REVIEW = os.getenv('ENABLE_BUSINESS_REVIEW', 'Admin Only').strip()
ENABLE_BUSINESS_REVIEW_PORTFOLIO = os.getenv('ENABLE_BUSINESS_REVIEW_PORTFOLIO', 'Admin Only').strip()
ENABLE_BUSINESS_OPPORTUNITY_ENGINE = os.getenv('ENABLE_BUSINESS_OPPORTUNITY_ENGINE', 'Admin Only').strip()
ENABLE_BUSINESS_RISK_ENGINE = os.getenv('ENABLE_BUSINESS_RISK_ENGINE', 'Admin Only').strip()
ENABLE_BUSINESS_REVIEW_ACTIONS = os.getenv('ENABLE_BUSINESS_REVIEW_ACTIONS', 'Admin Only').strip()
ENABLE_BUSINESS_REVIEW_DECISIONS = os.getenv('ENABLE_BUSINESS_REVIEW_DECISIONS', 'Admin Only').strip()
ENABLE_BUSINESS_REVIEW_AI_BRIEFING = os.getenv('ENABLE_BUSINESS_REVIEW_AI_BRIEFING', 'Disabled').strip()
ENABLE_BUSINESS_REVIEW_EXPORT = os.getenv('ENABLE_BUSINESS_REVIEW_EXPORT', 'Admin Only').strip()
ENABLE_BUSINESS_REVIEW_DRAFT_PREVIEW = os.getenv('ENABLE_BUSINESS_REVIEW_DRAFT_PREVIEW', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_V2 = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_V2', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_CUSTOMERS = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_CUSTOMERS', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_COUNTRIES = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_COUNTRIES', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_KEY_ACCOUNTS = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_KEY_ACCOUNTS', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_LAST_VISIT = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_LAST_VISIT', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_ATTENTION = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_ATTENTION', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_WATCHLIST = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_WATCHLIST', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_AI = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_AI', 'Disabled').strip()
ENABLE_BUSINESS_COMMAND_CENTER_EXPORT = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_EXPORT', 'Admin Only').strip()
ENABLE_BUSINESS_COMMAND_CENTER_PRESENTATION_MODE = os.getenv('ENABLE_BUSINESS_COMMAND_CENTER_PRESENTATION_MODE', 'Admin Only').strip()
ENABLE_USER_OWNS_DATA_EMBEDDING = os.getenv(
    'ENABLE_USER_OWNS_DATA_EMBEDDING', 'Production'
).strip()
ENABLE_ENTRA_ACCOUNT_LINKING = os.getenv(
    'ENABLE_ENTRA_ACCOUNT_LINKING', 'Production'
).strip()
ENTRA_REDIRECT_URI = os.getenv('ENTRA_REDIRECT_URI', '').strip()
ENTRA_POST_LOGOUT_REDIRECT_URI = os.getenv('ENTRA_POST_LOGOUT_REDIRECT_URI', '').strip()
ENABLE_DELEGATED_TOKEN_REFRESH = os.getenv(
    'ENABLE_DELEGATED_TOKEN_REFRESH', 'Production'
).strip()
FOLLOW_UP_MINIMUM_CONFIDENCE = int(os.getenv('FOLLOW_UP_MINIMUM_CONFIDENCE', '85'))
MAX_ACTIVE_CONVERSATIONS_PER_USER = int(os.getenv('MAX_ACTIVE_CONVERSATIONS_PER_USER', '10'))

ENABLE_DOWNTIME_MAPPING_CHECK = os.getenv('ENABLE_DOWNTIME_MAPPING_CHECK', 'Admin Only').strip()
ENABLE_FULL_AI_DOWNTIME_AUDIT = os.getenv('ENABLE_FULL_AI_DOWNTIME_AUDIT', 'Pilot').strip()
ENABLE_DOWNTIME_MAPPING_WRITEBACK = os.getenv('ENABLE_DOWNTIME_MAPPING_WRITEBACK', 'Disabled').strip()
ENABLE_DOWNTIME_MAPPING_BATCH_PROCESSING = os.getenv('ENABLE_DOWNTIME_MAPPING_BATCH_PROCESSING', 'Pilot').strip()
ENABLE_DOWNTIME_MAPPING_KNOWLEDGE_LEARNING = os.getenv('ENABLE_DOWNTIME_MAPPING_KNOWLEDGE_LEARNING', 'Admin Only').strip()
DOWNTIME_MAPPING_VERIFIED_THRESHOLD = int(os.getenv('DOWNTIME_MAPPING_VERIFIED_THRESHOLD', '90'))
DOWNTIME_MAPPING_MISMATCH_THRESHOLD = int(os.getenv('DOWNTIME_MAPPING_MISMATCH_THRESHOLD', '85'))
DOWNTIME_MAPPING_REVIEW_THRESHOLD = int(os.getenv('DOWNTIME_MAPPING_REVIEW_THRESHOLD', '70'))
DOWNTIME_MAPPING_MAX_DATE_RANGE_DAYS = int(os.getenv('DOWNTIME_MAPPING_MAX_DATE_RANGE_DAYS', '92'))
DOWNTIME_MAPPING_MAX_ROWS_PER_RUN = int(os.getenv('DOWNTIME_MAPPING_MAX_ROWS_PER_RUN', '5000'))
DOWNTIME_MAPPING_MAX_ESTIMATED_COST = float(os.getenv('DOWNTIME_MAPPING_MAX_ESTIMATED_COST', '20'))
DOWNTIME_MAPPING_DEV_THREAD_WORKER = os.getenv('DOWNTIME_MAPPING_DEV_THREAD_WORKER', 'true').lower() in {'1', 'true', 'yes', 'on'}
