# Generated by Django 6.0.6 on 2026-09-14 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodexDiagnosticRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='COMPLETED', max_length=30)),
                ('summary_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codex_diagnostic_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codex_diagnostic_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
